import { env } from 'cloudflare:test';
import { introspectWorkflowInstance } from 'cloudflare:test';
import { beforeAll,beforeEach,describe,expect,it } from 'vitest';

declare module 'cloudflare:test' {interface ProvidedEnv {DB:D1Database;EVENT_INTAKES:R2Bucket;WINE_SCOUT_SUBMISSION_WORKFLOW:Workflow<{submissionId:string}>;}}

beforeAll(async()=>{await env.DB.exec(`
	CREATE TABLE IF NOT EXISTS agent_submissions(id TEXT PRIMARY KEY,source TEXT NOT NULL,conversation_key TEXT NOT NULL,push_target TEXT,status TEXT NOT NULL,first_received_at TEXT NOT NULL,last_received_at TEXT NOT NULL,closed_at TEXT,workflow_instance_id TEXT UNIQUE,result_event_id TEXT,result_action TEXT,error_code TEXT,error_message TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
	CREATE TABLE IF NOT EXISTS agent_submission_items(id TEXT PRIMARY KEY,submission_id TEXT NOT NULL,source_message_id TEXT NOT NULL UNIQUE,webhook_event_id TEXT UNIQUE,item_type TEXT NOT NULL,asset_id TEXT UNIQUE,intake_id TEXT,r2_object_key TEXT,content_type TEXT,text_content TEXT,source_url TEXT,ordinal INTEGER NOT NULL,received_at TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(submission_id,ordinal));
	CREATE TABLE IF NOT EXISTS agent_submission_diagnostics(submission_id TEXT PRIMARY KEY,ai_result_json TEXT,validation_diagnostics_json TEXT NOT NULL DEFAULT '[]',matching_diagnostics_json TEXT NOT NULL DEFAULT '{}',uncertainty_reasons_json TEXT NOT NULL DEFAULT '[]',url_diagnostics_json TEXT NOT NULL DEFAULT '[]',raw_ai_r2_key TEXT,updated_at TEXT NOT NULL);
`);for(const sql of [`ALTER TABLE agent_submissions ADD COLUMN done_settle_until TEXT`,`ALTER TABLE agent_submissions ADD COLUMN closure_reason TEXT`])try{await env.DB.prepare(sql).run();}catch{/* shared test database may already be upgraded */}});
beforeEach(async()=>{await env.DB.exec('DELETE FROM agent_submission_diagnostics;DELETE FROM agent_submission_items;DELETE FROM agent_submissions;');});

describe('V2 durable inactivity closure',()=>{
	it('closes after the durable Workflow event timeout and processes once',async()=>{const submissionId=crypto.randomUUID();const old='2020-01-01T00:00:00.000Z';await env.EVENT_INTAKES.put(`workflow-test/${submissionId}.gif`,new Uint8Array([1,2,3]),{httpMetadata:{contentType:'image/gif'}});await env.DB.prepare(`INSERT INTO agent_submissions(id,source,conversation_key,status,first_received_at,last_received_at,created_at,updated_at) VALUES(?,'line_v2','user:test','collecting',?,?,?,?)`).bind(submissionId,old,old,old,old).run();await env.DB.prepare(`INSERT INTO agent_submission_items(id,submission_id,source_message_id,webhook_event_id,item_type,asset_id,intake_id,r2_object_key,content_type,ordinal,received_at,created_at) VALUES(?,?,?,?,'image',?,?,?,?,1,?,?)`).bind(`item-${submissionId}`,submissionId,`message-${submissionId}`,`webhook-${submissionId}`,`asset-${submissionId}`,`intake-${submissionId}`,`workflow-test/${submissionId}.gif`,'image/gif',old,old).run();const introspector=await introspectWorkflowInstance(env.WINE_SCOUT_SUBMISSION_WORKFLOW,submissionId);try{await introspector.modify(async(modifier)=>modifier.forceEventTimeout({name:'collect_submission_0'}));await env.WINE_SCOUT_SUBMISSION_WORKFLOW.create({id:submissionId,params:{submissionId}});await expect(introspector.waitForStatus('complete')).resolves.not.toThrow();expect(await env.DB.prepare('SELECT status,closed_at FROM agent_submissions WHERE id=?').bind(submissionId).first()).toMatchObject({status:'needs_review'});expect(await introspector.waitForStepResult({name:'close_inactive_submission_0'})).toBeUndefined();}finally{await introspector.dispose();}});
});
