import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from 'cloudflare:workers';
import { NonRetryableError } from 'cloudflare:workflows';
import type { WorkerEnv } from '../types/env';
import { pushToLine } from '../services/line';
import { readSubmission, saveSubmissionDiagnostics, setSubmissionStatus } from '../services/agent-submission-repository';
import { analyseSubmissionWithDiagnostics, persistEditorialEvent, prepareSubmissionContext, readPublishedEventSummary, resolveEventIdentity, validateEditorialProposal } from '../services/wine-scout-editorial-agent';
import { getIngestionMode, getV2PublicationControl, type PublicationControl } from '../services/runtime-controls';

export interface SubmissionWorkflowParams {submissionId:string;}
const duration=(seconds:number)=>`${Math.max(1,Math.min(86400,seconds))} seconds` as `${number} seconds`;
function log(fields:Record<string,unknown>):void{console.log(JSON.stringify({component:'agent_submission_v2',...fields}));}
function lineAccessToken(env:WorkerEnv):string{return env.LINE_V2_CHANNEL_ACCESS_TOKEN?.trim()||env.LINE_CHANNEL_ACCESS_TOKEN;}
export const PUBLICATION_DISABLED_REASON='V2 publication is disabled by the production safety control.';
export function publicationBlockedNotification():string{return `The event was received but needs review.\nReason: ${PUBLICATION_DISABLED_REASON}`;}
export function publicationBlockedTerminal():{status:'needs_review';errorCode:'publication_disabled';errorMessage:string}{return{status:'needs_review',errorCode:'publication_disabled',errorMessage:PUBLICATION_DISABLED_REASON};}
export type PersistenceBoundaryResult<T>={blocked:true;control:PublicationControl}|{blocked:false;control:PublicationControl;persisted:T};
export async function runV2PersistenceBoundary<T>(env:Pick<WorkerEnv,'DB'|'V2_PUBLICATION_ENABLED'|'INGESTION_MODE'>,submissionId:string,workflowInstanceId:string,persist:()=>Promise<T>):Promise<PersistenceBoundaryResult<T>>{
	const control=await getV2PublicationControl(env);
	if(!control.enabled){log({event:'PUBLICATION_BLOCKED',pipeline:'v2',ingestionMode:getIngestionMode(env),submissionId,workflowInstanceId,reason:'v2_publication_disabled',controlSource:control.source,timestamp:new Date().toISOString()});return{blocked:true,control};}
	return{blocked:false,control,persisted:await persist()};
}

export class WineScoutSubmissionWorkflow extends WorkflowEntrypoint<WorkerEnv,SubmissionWorkflowParams>{
	async run(event:WorkflowEvent<SubmissionWorkflowParams>,step:WorkflowStep):Promise<void>{const submissionId=event.payload.submissionId;const started=Date.now();
		try{
			log({event:'analysis_started',submissionId,workflowInstanceId:event.instanceId,status:'running',step:'workflow'});
			let submission=await step.do('load_submission',()=>readSubmission(this.env.DB,submissionId));if(!submission)throw new Error('submission_not_found');
			const windowSeconds=Number(this.env.AGENT_SUBMISSION_WINDOW_SECONDS||'60');
			for(let wait=0;submission.status==='collecting'&&wait<100;wait++){
				const inactivityExpiresAt=Date.parse(submission.lastReceivedAt)+windowSeconds*1000;const settlementExpiresAt=submission.doneSettleUntil?Date.parse(submission.doneSettleUntil):Number.POSITIVE_INFINITY;const expiresAt=Math.min(inactivityExpiresAt,settlementExpiresAt);const remaining=Math.max(1,Math.ceil((expiresAt-Date.now())/1000));
				try{await step.waitForEvent(`collect_submission_${wait}`,{type:'submission-updated',timeout:duration(remaining)});}catch{/* inactivity timeout is expected */}
				submission=await step.do(`reload_submission_${wait}`,()=>readSubmission(this.env.DB,submissionId));if(!submission)throw new Error('submission_not_found');
				if(submission.status==='collecting'&&submission.doneSettleUntil&&Date.parse(submission.doneSettleUntil)<=Date.now())await step.do(`close_done_settlement_${wait}`,async()=>{const now=new Date().toISOString();await this.env.DB.prepare("UPDATE agent_submissions SET status='queued',closed_at=?,closure_reason='done_settlement_timeout',updated_at=? WHERE id=? AND status='collecting' AND done_settle_until=?").bind(now,now,submissionId,submission!.doneSettleUntil).run();});
				else if(submission.status==='collecting'&&Date.parse(submission.lastReceivedAt)+windowSeconds*1000<=Date.now())await step.do(`close_inactive_submission_${wait}`,async()=>{const now=new Date().toISOString();await this.env.DB.prepare("UPDATE agent_submissions SET status='queued',closed_at=?,closure_reason='inactivity_timeout',updated_at=? WHERE id=? AND status='collecting' AND last_received_at=?").bind(now,now,submissionId,submission!.lastReceivedAt).run();});
				submission=await readSubmission(this.env.DB,submissionId)??submission;
			}
			if(submission.status==='published'||submission.status==='needs_review')return;if(submission.status==='collecting')throw new Error('submission_collection_limit_reached');
			await step.do('mark_processing',()=>setSubmissionStatus(this.env.DB,submissionId,'processing'));
			const prepared=JSON.parse(await step.do('prepare_submission_context',async()=>JSON.stringify(await prepareSubmissionContext(this.env,submissionId)))) as Awaited<ReturnType<typeof prepareSubmissionContext>>;
			const analysis=JSON.parse(await step.do('analyse_submission',{retries:{limit:3,delay:'30 seconds',backoff:'exponential'}},async()=>{try{return JSON.stringify(await analyseSubmissionWithDiagnostics(this.env,prepared));}catch(error){const message=error instanceof Error?error.message:String(error);if(/4006|daily free allocation|quota|billing|upgrade/i.test(message))throw new NonRetryableError(message,'ai_capacity_exhausted');throw error;}})) as Awaited<ReturnType<typeof analyseSubmissionWithDiagnostics>>;const proposal=analysis.proposal;
			const validation=JSON.parse(await step.do('validate_ai_result',async()=>{const result=validateEditorialProposal(proposal,prepared);await saveSubmissionDiagnostics(this.env.DB,submissionId,{aiResult:proposal,validation:result,uncertainties:proposal.uncertainties,urls:prepared.urlDiagnostics,rawAiR2Key:`agent-submissions/${submissionId}/ai-result.json`});return JSON.stringify(result);})) as ReturnType<typeof validateEditorialProposal>;
			const candidates=await step.do('find_candidate_events',async()=>JSON.stringify(validation.normalized?await resolveEventIdentity(this.env,proposal,validation.normalized):null));
			const identity=JSON.parse(await step.do('resolve_event_identity',async()=>candidates)) as Awaited<ReturnType<typeof resolveEventIdentity>>|null;
			if(!validation.publishable||!validation.normalized||!identity||identity.decision==='conflict'){
				const reasons=[...validation.reasons,...(identity?.decision==='conflict'?['multiple existing events match strongly']:[])];await step.do('persist_review_result',async()=>{await saveSubmissionDiagnostics(this.env.DB,submissionId,{aiResult:proposal,validation:{...validation,reasons},matching:identity?.diagnostics??{},uncertainties:[...proposal.uncertainties,...reasons],urls:prepared.urlDiagnostics,rawAiR2Key:`agent-submissions/${submissionId}/ai-result.json`});await setSubmissionStatus(this.env.DB,submissionId,'needs_review',{errorCode:'review_required',errorMessage:reasons.join('; ')});});
				await step.do('finalize_submission',async()=>undefined);await step.do('notify_line',async()=>{if(!submission!.pushTarget)return;try{await pushToLine(submission!.pushTarget!,`The event was received but needs review.\nReason: ${reasons[0]??'Insufficient or conflicting evidence'}`,lineAccessToken(this.env));}catch(error){log({submissionId,workflowInstanceId:event.instanceId,status:'needs_review',step:'notify_line',errorCode:error instanceof Error?error.message:String(error)});}});log({event:'analysis_completed',submissionId,workflowInstanceId:event.instanceId,model:analysis.model,includedAssetCount:analysis.includedAssetCount,includedImageBytes:analysis.includedImageBytes,decision:proposal.decision,confidence:proposal.confidence,resultEventId:null,status:'needs_review',step:'complete',duration:Date.now()-started});return;
			}
			const persistence=JSON.parse(await step.do('persist_event',async()=>JSON.stringify(await runV2PersistenceBoundary(this.env,submissionId,event.instanceId,()=>persistEditorialEvent(this.env,submissionId,prepared,proposal,validation.normalized!,identity))))) as PersistenceBoundaryResult<Awaited<ReturnType<typeof persistEditorialEvent>>>;
			if(persistence.blocked){await step.do('persist_publication_blocked',async()=>{const terminal=publicationBlockedTerminal();await saveSubmissionDiagnostics(this.env.DB,submissionId,{aiResult:proposal,validation:{...validation,publishable:false,reasons:[...validation.reasons,PUBLICATION_DISABLED_REASON],rejectionStage:'publication_guard'},matching:identity.diagnostics,uncertainties:[...proposal.uncertainties,PUBLICATION_DISABLED_REASON],urls:prepared.urlDiagnostics,rawAiR2Key:`agent-submissions/${submissionId}/ai-result.json`});await setSubmissionStatus(this.env.DB,submissionId,terminal.status,{errorCode:terminal.errorCode,errorMessage:terminal.errorMessage});});await step.do('notify_line_publication_blocked',async()=>{if(!submission!.pushTarget)return;try{await pushToLine(submission!.pushTarget!,publicationBlockedNotification(),lineAccessToken(this.env));}catch(error){log({submissionId,workflowInstanceId:event.instanceId,status:'needs_review',step:'notify_line_publication_blocked',errorCode:error instanceof Error?error.message:String(error)});}});log({event:'analysis_completed',submissionId,workflowInstanceId:event.instanceId,resultEventId:null,status:'needs_review',step:'complete',reason:'publication_disabled',duration:Date.now()-started});return;}
			const persisted=persistence.persisted;
			await step.do('finalize_submission',()=>setSubmissionStatus(this.env.DB,submissionId,'published',{eventId:persisted.eventId,action:persisted.updated?'updated':'published'}));
			await step.do('notify_line',async()=>{if(!submission!.pushTarget)return;try{const eventSummary=await readPublishedEventSummary(this.env.DB,persisted.eventId);const origin=this.env.PUBLIC_SITE_ORIGIN?.replace(/\/$/,'');const url=origin&&eventSummary.slug?`${origin}/events/${encodeURIComponent(eventSummary.slug)}`:'';await pushToLine(submission!.pushTarget!,`${persisted.updated?'Existing event updated':'Event published'}: ${eventSummary.title}${url?`\n${url}`:''}`,lineAccessToken(this.env));}catch(error){log({submissionId,workflowInstanceId:event.instanceId,status:'published',step:'notify_line',eventId:persisted.eventId,errorCode:error instanceof Error?error.message:String(error)});}});
			log({event:'analysis_completed',submissionId,workflowInstanceId:event.instanceId,model:analysis.model,includedAssetCount:analysis.includedAssetCount,includedImageBytes:analysis.includedImageBytes,decision:proposal.decision,confidence:proposal.confidence,resultEventId:persisted.eventId,status:'published',step:'complete',duration:Date.now()-started});
		}catch(error){const message=error instanceof Error?error.message:String(error);await step.do('record_workflow_failure',()=>setSubmissionStatus(this.env.DB,submissionId,'failed',{errorCode:'workflow_failed',errorMessage:message}));log({event:'analysis_failed',submissionId,workflowInstanceId:event.instanceId,status:'failed',step:'workflow',errorCode:'workflow_failed',errorMessage:message,duration:Date.now()-started});throw error;}
	}
}
