import { APP_NAME, VERSION, getAgentDoneSettlementSeconds, getAgentSubmissionWindowSeconds } from '../config';
import type { WorkerEnv } from '../types/env';
import type { LineImageMessageEvent, LineTextMessageEvent, LineWebhookPayload } from '../types/line';
import { buildLineConversationKey } from '../services/line-text-context';
import { downloadLineMessageContent, replyToLine } from '../services/line';
import { storeLineImageAsset } from '../services/event-intake';
import { appendSubmissionItem, closeSubmissionForDone, findSubmissionForMessage } from '../services/agent-submission-repository';
import { ensureAgentSubmissionWorkflow } from '../services/agent-submission-reconciliation';
import { detectPrimaryWebUrl } from '../services/web-page-ingestion-service';

const RECEIVED='Received – Bangkok Wine Scout is collecting the event information.\nSend more material or type /done to process it now.';
const CLOSED='Submission closed – analysis is starting now.';
const encoder=new TextEncoder();
function pushTarget(event:{source?:{userId?:string;groupId?:string;roomId?:string}}):string|undefined{return event.source?.userId??event.source?.groupId??event.source?.roomId;}
function isText(event:unknown):event is LineTextMessageEvent{return (event as LineTextMessageEvent)?.type==='message'&&(event as LineTextMessageEvent)?.message?.type==='text';}
function isImage(event:unknown):event is LineImageMessageEvent{return (event as LineImageMessageEvent)?.type==='message'&&(event as LineImageMessageEvent)?.message?.type==='image';}
function isPdf(event:unknown):event is {type:'message';replyToken:string;message:{id:string;type:'file';fileName:string}}{const candidate=event as {type?:unknown;replyToken?:unknown;message?:{id?:unknown;type?:unknown;fileName?:unknown}};return candidate?.type==='message'&&candidate.message?.type==='file'&&typeof candidate.replyToken==='string'&&typeof candidate.message.id==='string'&&typeof candidate.message.fileName==='string'&&candidate.message.fileName.toLowerCase().endsWith('.pdf');}
export function getLineV2AccessToken(env:WorkerEnv):string{return env.LINE_V2_CHANNEL_ACCESS_TOKEN?.trim()||env.LINE_CHANNEL_ACCESS_TOKEN;}

export async function verifyLineSignature(rawBody:string,signature:string|null,secret:string):Promise<boolean>{if(!signature||!secret)return false;const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await crypto.subtle.sign('HMAC',key,encoder.encode(rawBody));const expected=btoa(String.fromCharCode(...new Uint8Array(digest)));if(expected.length!==signature.length)return false;let mismatch=0;for(let index=0;index<expected.length;index++)mismatch|=expected.charCodeAt(index)^signature.charCodeAt(index);return mismatch===0;}

const ensureWorkflow=(env:WorkerEnv,submissionId:string)=>ensureAgentSubmissionWorkflow(env,submissionId,'webhook').then(()=>undefined);

export async function processAgentWebhookEvents(body:LineWebhookPayload,env:WorkerEnv):Promise<void>{const webhookBatchId=crypto.randomUUID();const events=body.events??[];const imageEventCount=events.filter(isImage).length;console.log(JSON.stringify({component:'agent_submission_v2',event:'webhook_received',webhookEventCount:events.length,imageEventCount}));for(const raw of events){if(isPdf(raw)){try{await replyToLine(raw.replyToken,'PDF files aren’t supported yet. Please send the flyer pages as images instead. You can send multiple images — Bangkok Wine Scout will process them together as one event.',getLineV2AccessToken(env));}catch(error){console.error('LINE V2 PDF ACK FAILED',error);}continue;}if(!isText(raw)&&!isImage(raw))continue;const conversationKey=buildLineConversationKey(raw.source);if(!conversationKey)continue;const receivedAt=new Date(raw.timestamp??Date.now()).toISOString();const messageId=raw.message.id;const webhookEventId=raw.webhookEventId;const duplicate=await findSubmissionForMessage(env.DB,messageId,webhookEventId);if(duplicate){continue;}
		if(isText(raw)&&raw.message.text.trim().toLowerCase()==='/done'){const closed=await closeSubmissionForDone(env.DB,{conversationKey,sourceMessageId:messageId,webhookEventId,receivedAt,settlementSeconds:getAgentDoneSettlementSeconds(env),closedAcknowledgement:CLOSED,emptyAcknowledgement:'No V2 submission is currently collecting.'});if(closed.submission&&!closed.duplicate)await ensureWorkflow(env,closed.submission.id);if(!closed.duplicate)try{await replyToLine(raw.replyToken,closed.acknowledgement,getLineV2AccessToken(env));}catch(error){console.error('LINE V2 ACK FAILED',error);}continue;}
		let item:{itemType:'image'|'text'|'url';assetId?:string;intakeId?:string;r2ObjectKey?:string;contentType?:string;textContent?:string;sourceUrl?:string};
		if(isImage(raw)){const downloaded=await downloadLineMessageContent(messageId,getLineV2AccessToken(env));const stored=await storeLineImageAsset(env.EVENT_INTAKES,{intakeId:`agent-line-${messageId}`,sourceType:'line_image',sourceReference:messageId,lineUserId:raw.source?.userId,receivedAt,contentType:downloaded.contentType,content:downloaded.content});item={itemType:'image',assetId:stored.assetId,intakeId:stored.intakeId,r2ObjectKey:stored.objectKey,contentType:downloaded.contentType};}
		else{const detected=detectPrimaryWebUrl(raw.message.text);item=detected?{itemType:'url',sourceUrl:detected.normalizedUrl,textContent:raw.message.text,contentType:'text/uri-list'}:{itemType:'text',textContent:raw.message.text,contentType:'text/plain'};}
		const imageSet=isImage(raw)?raw.message.imageSet:undefined;const registered=await appendSubmissionItem(env.DB,{conversationKey,pushTarget:pushTarget(raw),sourceMessageId:messageId,webhookEventId,itemType:item.itemType,assetId:item.assetId,intakeId:item.intakeId,r2ObjectKey:item.r2ObjectKey,contentType:item.contentType,textContent:item.textContent,sourceUrl:item.sourceUrl,receivedAt,windowSeconds:getAgentSubmissionWindowSeconds(env),imageSetId:imageSet?.id,imageSetIndex:imageSet?.index,imageSetTotal:imageSet?.total,webhookBatchId,webhookEventCount:events.length,imageEventCount});console.log(JSON.stringify({component:'agent_submission_v2',event:'item_registered',submissionId:registered.submission.id,imageSetId:imageSet?.id??null,expectedImageCount:imageSet?.total??null,imageSetIndex:imageSet?.index??null,groupingStrategy:registered.submission.groupingStrategy,appendRaceResolution:registered.appendRaceResolved?'resolved':'not_needed'}));if(registered.expiredSubmissionId)await ensureWorkflow(env,registered.expiredSubmissionId);await ensureWorkflow(env,registered.submission.id);if(!registered.duplicate)try{await replyToLine(raw.replyToken,RECEIVED,getLineV2AccessToken(env));}catch(error){console.error('LINE V2 ACK FAILED',error);}
	}}

export async function handleAgentWebhookV2(request:Request,env:WorkerEnv,ctx?:ExecutionContext):Promise<Response>{if(!env.LINE_V2_CHANNEL_SECRET)return Response.json({status:'error',message:'V2 LINE channel secret is not configured'},{status:503});const rawBody=await request.text();if(!await verifyLineSignature(rawBody,request.headers.get('x-line-signature'),env.LINE_V2_CHANNEL_SECRET))return Response.json({status:'error',message:'Invalid LINE signature'},{status:401});let body:LineWebhookPayload;try{body=JSON.parse(rawBody) as LineWebhookPayload;}catch{return Response.json({status:'error',message:'Invalid request body'},{status:400});}const work=processAgentWebhookEvents(body,env);if(ctx)ctx.waitUntil(work);else await work;return Response.json({status:'ok',received:true,service:APP_NAME,version:VERSION});}
