import { env } from 'cloudflare:test';
import { beforeAll,beforeEach,describe,expect,it,vi } from 'vitest';
import type { WorkerEnv } from '../types/env';
import type { LineWebhookPayload } from '../types/line';
import { processAgentWebhookEvents,verifyLineSignature } from './agent-webhook-v2';

const mocks=vi.hoisted(()=>({reply:vi.fn().mockResolvedValue(undefined),download:vi.fn().mockResolvedValue({content:new ArrayBuffer(3),contentType:'image/jpeg'}),store:vi.fn().mockImplementation(async(_bucket,input)=>({intakeId:input.intakeId,assetId:`line-message-${input.sourceReference}`,objectKey:`intakes/${input.intakeId}/assets/line-message-${input.sourceReference}/original`,metadataKey:'meta',contentHash:'hash',duplicate:false}))}));
vi.mock('../services/line',()=>({replyToLine:mocks.reply,downloadLineMessageContent:mocks.download}));
vi.mock('../services/event-intake',()=>({storeLineImageAsset:mocks.store}));

const instances=new Map<string,{id:string;sendEvent:ReturnType<typeof vi.fn>;status:ReturnType<typeof vi.fn>;restart:ReturnType<typeof vi.fn>;resume:ReturnType<typeof vi.fn>}>();const create=vi.fn(async({id}:{id:string})=>{const instance={id,sendEvent:vi.fn().mockResolvedValue(undefined),status:vi.fn().mockResolvedValue({status:'running'}),restart:vi.fn(),resume:vi.fn()};instances.set(id,instance);return instance;});const get=vi.fn(async(id:string)=>instances.get(id)!);
const schema=`CREATE TABLE IF NOT EXISTS agent_submissions(id TEXT PRIMARY KEY,source TEXT NOT NULL,conversation_key TEXT NOT NULL,push_target TEXT,status TEXT NOT NULL,first_received_at TEXT NOT NULL,last_received_at TEXT NOT NULL,closed_at TEXT,workflow_instance_id TEXT UNIQUE,result_event_id TEXT,result_action TEXT,error_code TEXT,error_message TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS agent_active_test ON agent_submissions(source,conversation_key) WHERE status='collecting';CREATE TABLE IF NOT EXISTS agent_submission_items(id TEXT PRIMARY KEY,submission_id TEXT NOT NULL,source_message_id TEXT NOT NULL UNIQUE,webhook_event_id TEXT UNIQUE,item_type TEXT NOT NULL,asset_id TEXT UNIQUE,intake_id TEXT,r2_object_key TEXT,content_type TEXT,text_content TEXT,source_url TEXT,ordinal INTEGER NOT NULL,received_at TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(submission_id,ordinal));CREATE TABLE IF NOT EXISTS agent_v2_webhook_receipts(webhook_event_id TEXT PRIMARY KEY,source_message_id TEXT NOT NULL UNIQUE,submission_id TEXT,acknowledgement_text TEXT NOT NULL,created_at TEXT NOT NULL);`;
const upgrades=`ALTER TABLE agent_submissions ADD COLUMN image_set_id TEXT;ALTER TABLE agent_submissions ADD COLUMN expected_image_count INTEGER;ALTER TABLE agent_submissions ADD COLUMN grouping_strategy TEXT;ALTER TABLE agent_submissions ADD COLUMN done_requested_at TEXT;ALTER TABLE agent_submissions ADD COLUMN done_settle_until TEXT;ALTER TABLE agent_submissions ADD COLUMN closure_reason TEXT;ALTER TABLE agent_submissions ADD COLUMN append_race_count INTEGER NOT NULL DEFAULT 0;ALTER TABLE agent_submissions ADD COLUMN webhook_event_count INTEGER NOT NULL DEFAULT 0;ALTER TABLE agent_submissions ADD COLUMN image_event_count INTEGER NOT NULL DEFAULT 0;ALTER TABLE agent_submission_items ADD COLUMN image_set_id TEXT;ALTER TABLE agent_submission_items ADD COLUMN image_set_index INTEGER;ALTER TABLE agent_submission_items ADD COLUMN image_set_total INTEGER;ALTER TABLE agent_submission_items ADD COLUMN webhook_batch_id TEXT;ALTER TABLE agent_submission_items ADD COLUMN append_race_resolved INTEGER NOT NULL DEFAULT 0;`;
beforeAll(async()=>{await env.DB.exec(schema);for(const sql of upgrades.split(';').filter(Boolean))try{await env.DB.prepare(sql).run();}catch{/* shared test database may already be upgraded */}});
beforeEach(async()=>{await env.DB.exec('DELETE FROM agent_v2_webhook_receipts;DELETE FROM agent_submission_items;DELETE FROM agent_submissions;');instances.clear();create.mockClear();get.mockClear();mocks.reply.mockClear();mocks.download.mockClear();mocks.store.mockClear();});
const testEnv=(window='60')=>({...env,AGENT_SUBMISSION_WINDOW_SECONDS:window,LINE_CHANNEL_ACCESS_TOKEN:'token',WINE_SCOUT_SUBMISSION_WORKFLOW:{create,get}}) as unknown as WorkerEnv;
function image(id:string,at='2026-08-04T10:00:00.000Z'):LineWebhookPayload{return{events:[{type:'message',replyToken:`reply-${id}`,timestamp:Date.parse(at),webhookEventId:`webhook-${id}`,source:{userId:'u1'},message:{id,type:'image'}}]};}
function imageEvent(id:string,index:number,total:number,setId='set-many',at='2026-08-04T10:00:00.000Z'){return{type:'message' as const,replyToken:`reply-${id}`,timestamp:Date.parse(at),webhookEventId:`webhook-${id}`,source:{userId:'u1'},message:{id,type:'image' as const,imageSet:{id:setId,index,total}}};}
function imagesInOnePost(total:number):LineWebhookPayload{return{events:Array.from({length:total},(_,index)=>imageEvent(`image-${index+1}`,index+1,total))};}
function text(id:string,value:string,at='2026-08-04T10:00:10.000Z'):LineWebhookPayload{return{events:[{type:'message',replyToken:`reply-${id}`,timestamp:Date.parse(at),webhookEventId:`webhook-${id}`,source:{userId:'u1'},message:{id,type:'text',text:value}}]};}

describe('LINE V2 mailbox',()=>{
	it('rejects PDF files without creating a submission',async()=>{
		const payload={
			events:[{
				type:'message',
				replyToken:'reply-pdf',
				webhookEventId:'webhook-pdf',
				timestamp:Date.parse('2026-08-04T10:00:00.000Z'),
				source:{userId:'u1'},
				message:{id:'pdf-1',type:'file',fileName:'wine-dinner.pdf'},
			}],
		} as unknown as LineWebhookPayload;
		await processAgentWebhookEvents(payload,testEnv());
		expect(mocks.reply).toHaveBeenCalledWith(
			'reply-pdf',
			'PDF files aren’t supported yet. Please send the flyer pages as images instead. You can send multiple images — Bangkok Wine Scout will process them together as one event.',
			'token',
		);
		expect(mocks.download).not.toHaveBeenCalled();
		expect(mocks.store).not.toHaveBeenCalled();
		expect(create).not.toHaveBeenCalled();
		expect((await env.DB.prepare('SELECT COUNT(*) count FROM agent_submissions').first<{count:number}>())?.count).toBe(0);
	});
	it('creates an image submission and stores its R2 asset reference',async()=>{await processAgentWebhookEvents(image('flyer'),testEnv());expect(await env.DB.prepare('SELECT item_type,asset_id,r2_object_key FROM agent_submission_items').first()).toMatchObject({item_type:'image',asset_id:'line-message-flyer'});expect(create).toHaveBeenCalledOnce();});
	it.each([2,3,7])('stores every image from a single webhook POST containing %i image events',async(total)=>{await processAgentWebhookEvents(imagesInOnePost(total),testEnv());expect(await env.DB.prepare('SELECT COUNT(*) count FROM agent_submissions').first<{count:number}>()).toMatchObject({count:1});expect(await env.DB.prepare('SELECT COUNT(*) count FROM agent_submission_items').first<{count:number}>()).toMatchObject({count:total});expect(mocks.download).toHaveBeenCalledTimes(total);expect(instances.size).toBe(1);});
	it('groups simultaneous separate webhook POSTs and atomically assigns every ordinal',async()=>{const total=8,worker=testEnv();await Promise.all(Array.from({length:total},(_,index)=>processAgentWebhookEvents({events:[imageEvent(`parallel-${index+1}`,index+1,total,'parallel-set')]},worker)));const rows=await env.DB.prepare('SELECT ordinal FROM agent_submission_items ORDER BY ordinal').all<{ordinal:number}>();expect(await env.DB.prepare('SELECT COUNT(*) count FROM agent_submissions').first<{count:number}>()).toMatchObject({count:1});expect(rows.results.map(row=>row.ordinal)).toEqual(Array.from({length:total},(_,index)=>index+1));expect(instances.size).toBe(1);});
	it('returns an out-of-order image set in LINE imageSet index order',async()=>{await processAgentWebhookEvents({events:[imageEvent('third',3,3),imageEvent('first',1,3),imageEvent('second',2,3)]},testEnv());const {listSubmissionItems}=await import('../services/agent-submission-repository');const submission=await env.DB.prepare('SELECT id FROM agent_submissions').first<{id:string}>();expect((await listSubmissionItems(env.DB,submission!.id)).map(item=>item.imageSetIndex)).toEqual([1,2,3]);});
	it('keeps /done collecting until a missing image-set member arrives',async()=>{const worker=testEnv();await processAgentWebhookEvents({events:[imageEvent('first',1,2,'settle-set')]},worker);await processAgentWebhookEvents(text('done-early','/done','2026-08-04T10:00:01.000Z'),worker);expect(await env.DB.prepare('SELECT status,closure_reason FROM agent_submissions').first()).toMatchObject({status:'collecting',closure_reason:'done_settling'});await processAgentWebhookEvents({events:[imageEvent('second',2,2,'settle-set','2026-08-04T10:00:02.000Z')]},worker);expect(await env.DB.prepare('SELECT status,closure_reason,expected_image_count FROM agent_submissions').first()).toMatchObject({status:'queued',closure_reason:'done_all_expected_images',expected_image_count:2});expect(await env.DB.prepare('SELECT COUNT(*) count FROM agent_submission_items').first<{count:number}>()).toMatchObject({count:2});});
	it('joins text to the same collecting submission',async()=>{const worker=testEnv();await processAgentWebhookEvents(image('flyer'),worker);await processAgentWebhookEvents(text('details','Wine dinner in Bangkok'),worker);expect((await env.DB.prepare('SELECT COUNT(*) count FROM agent_submissions').first<{count:number}>())?.count).toBe(1);expect((await env.DB.prepare('SELECT COUNT(*) count FROM agent_submission_items').first<{count:number}>())?.count).toBe(2);});
	it('stores a URL without fetching it in the webhook',async()=>{const fetchSpy=vi.spyOn(globalThis,'fetch');await processAgentWebhookEvents(text('url','See https://example.com/wine'),testEnv());expect(await env.DB.prepare('SELECT item_type,source_url,text_content FROM agent_submission_items').first()).toMatchObject({item_type:'url',source_url:'https://example.com/wine'});expect(fetchSpy).not.toHaveBeenCalled();fetchSpy.mockRestore();});
	it('/done atomically closes and signals exactly one Workflow instance',async()=>{const worker=testEnv();await processAgentWebhookEvents(text('details','Wine dinner'),worker);await processAgentWebhookEvents(text('done','/done'),worker);expect(await env.DB.prepare('SELECT status,closed_at FROM agent_submissions').first()).toMatchObject({status:'queued'});expect(create).toHaveBeenCalledOnce();expect(instances.size).toBe(1);expect(mocks.reply).toHaveBeenLastCalledWith('reply-done','Submission closed – analysis is starting now.','token');});
	it('suppresses a duplicate /done delivery',async()=>{const worker=testEnv();await processAgentWebhookEvents(text('details','Wine dinner'),worker);const done=text('done','/done');await processAgentWebhookEvents(done,worker);const instance=instances.values().next().value!;const signals=instance.sendEvent.mock.calls.length;await processAgentWebhookEvents(done,worker);expect(instance.sendEvent).toHaveBeenCalledTimes(signals);expect(mocks.reply.mock.calls.filter(([token])=>token==='reply-done')).toHaveLength(1);});
	it('expires an inactive submission without duplicating its Workflow instance',async()=>{const worker=testEnv('60');await processAgentWebhookEvents(text('one','First','2026-08-04T10:00:00.000Z'),worker);const firstInstanceId=[...instances.keys()][0];await processAgentWebhookEvents(text('two','Second','2026-08-04T10:01:01.000Z'),worker);const rows=await env.DB.prepare('SELECT id,status,workflow_instance_id FROM agent_submissions ORDER BY first_received_at').all<{id:string;status:string;workflow_instance_id:string}>();expect(rows.results.map((row)=>row.status)).toEqual(['queued','collecting']);expect(rows.results[0].workflow_instance_id).toBe(firstInstanceId);expect(create).toHaveBeenCalledTimes(2);expect(instances.size).toBe(2);});
	it('suppresses duplicate storage, workflow creation, and acknowledgement',async()=>{const payload=image('same');const worker=testEnv();await processAgentWebhookEvents(payload,worker);await processAgentWebhookEvents(payload,worker);expect((await env.DB.prepare('SELECT COUNT(*) count FROM agent_submission_items').first<{count:number}>())?.count).toBe(1);expect(mocks.download).toHaveBeenCalledOnce();expect(create).toHaveBeenCalledOnce();expect(mocks.reply).toHaveBeenCalledOnce();});
	it('validates LINE HMAC signatures',async()=>{const body='{"events":[]}';const key=await crypto.subtle.importKey('raw',new TextEncoder().encode('secret'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body));const signature=btoa(String.fromCharCode(...new Uint8Array(digest)));expect(await verifyLineSignature(body,signature,'secret')).toBe(true);expect(await verifyLineSignature(body,'bad','secret')).toBe(false);});
});
