import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { WorkerEnv } from '../types/env';
import { ensureBatchProcessingScheduledAfterAssetCompletion, processImageMessage, type ImageProcessingMessage } from './webhook';

const mocks=vi.hoisted(()=>({download:vi.fn(),store:vi.fn(),ocr:vi.fn(),save:vi.fn(),qr:vi.fn(),claim:vi.fn(),claimShell:vi.fn(),markShell:vi.fn(),complete:vi.fn(),fail:vi.fn(),getBatch:vi.fn(),markAttemptLimit:vi.fn()}));
vi.mock('../services/line',()=>({downloadLineMessageContent:mocks.download,pushToLine:vi.fn(),replyToLine:vi.fn()}));
vi.mock('../services/event-intake',()=>({storeLineImageAsset:mocks.store}));
vi.mock('../services/ocr',()=>({extractAndStoreOcr:mocks.ocr}));
vi.mock('../services/event-repository',()=>({saveWineEvent:mocks.save}));
vi.mock('../services/event-enrichment-repository',()=>({initializeEventEnrichment:vi.fn(),recordAssetEnrichment:vi.fn()}));
vi.mock('../services/qr-decoder',()=>({inspectAndStoreQr:mocks.qr}));
vi.mock('../services/line-image-batch-repository',()=>({claimBatchAssetProcessing:mocks.claim,claimBatchEventShell:mocks.claimShell,markBatchEventShellCreated:mocks.markShell,completeBatchAssetProcessing:mocks.complete,failBatchAssetProcessing:mocks.fail,getBatch:mocks.getBatch,markAssetAttemptLimitForReconciliation:mocks.markAttemptLimit}));

const send=vi.fn();
const env={LINE_CHANNEL_ACCESS_TOKEN:'token',EVENT_INTAKES:{put:vi.fn()},DB:{},AI:{},IMAGE_PROCESSING_QUEUE:{send},LINE_MESSAGE_BATCH_WINDOW_SECONDS:'60',LINE_IMAGE_BATCH_WINDOW_SECONDS:'15',LINE_TEXT_CONTEXT_WINDOW_SECONDS:'600'} as unknown as WorkerEnv;
const message:ImageProcessingMessage={type:'process_image',batchId:'b1',assetId:'line-message-m1',sourceMessageId:'m1',messageId:'m1',conversationKey:'user:u1',pushTarget:'u1',receivedAt:'2026-08-01T00:00:00.000Z'};

beforeEach(()=>{vi.useRealTimers();vi.clearAllMocks();mocks.claim.mockResolvedValue('claimed');mocks.claimShell.mockResolvedValue({eventId:'line-batch:b1',anchorAssetId:'line-message-m1',isAnchor:true,shellCreatedAt:null});mocks.markShell.mockResolvedValue(true);mocks.complete.mockResolvedValue(true);mocks.fail.mockResolvedValue(true);mocks.getBatch.mockResolvedValue(null);mocks.download.mockResolvedValue({contentType:'image/jpeg',content:new Uint8Array([1]).buffer});mocks.store.mockResolvedValue({intakeId:'line-m1',assetId:'line-message-m1',objectKey:'objects/a1',duplicate:false});mocks.save.mockResolvedValue({id:'event-1',duplicate:false});mocks.qr.mockResolvedValue({status:'not_available',values:[]});mocks.ocr.mockResolvedValue({status:'completed',text:'Wine dinner',model:'ocr'});send.mockResolvedValue(undefined)});

describe('LINE image registration',()=>{
	it('updates the synchronously registered placeholder after storing the image',async()=>{await processImageMessage(message,env);expect(mocks.claim).toHaveBeenCalledWith(env.DB,'b1','line-message-m1');expect(mocks.complete).toHaveBeenCalledWith(env.DB,'b1','line-message-m1',expect.objectContaining({intakeId:'line-m1',contentType:'image/jpeg',r2ObjectKey:'objects/a1'}))});
	it('suppresses duplicate queue delivery after completion',async()=>{mocks.claim.mockResolvedValue('completed');await processImageMessage(message,env);expect(mocks.download).not.toHaveBeenCalled();expect(mocks.complete).not.toHaveBeenCalled()});
	it('marks the existing placeholder failed and retries the queue message when download fails',async()=>{mocks.download.mockRejectedValue(new Error('LINE download failed'));await expect(processImageMessage(message,env)).rejects.toThrow('LINE download failed');expect(mocks.fail).toHaveBeenCalledWith(env.DB,'b1','line-message-m1',expect.any(Error));expect(mocks.complete).not.toHaveBeenCalled()});
	it('completes the stored flyer when OCR enrichment fails',async()=>{mocks.ocr.mockResolvedValue({status:'failed',text:'',error:'model unavailable'});await processImageMessage(message,env);expect(mocks.fail).not.toHaveBeenCalled();expect(mocks.complete).toHaveBeenCalledWith(env.DB,'b1','line-message-m1',expect.objectContaining({intakeId:'line-m1',contentType:'image/jpeg',r2ObjectKey:'objects/a1'}))});
	it('keeps the R2 flyer and records retryable reconciliation state when minimal D1 publication is unavailable',async()=>{mocks.save.mockRejectedValue(new Error('D1 unavailable'));await expect(processImageMessage(message,env)).rejects.toThrow('D1 unavailable');expect(mocks.store).toHaveBeenCalledOnce();expect((env.EVENT_INTAKES.put as ReturnType<typeof vi.fn>).mock.calls.some(([,body])=>String(body).includes('"status": "retryable"'))).toBe(true);expect(mocks.ocr).not.toHaveBeenCalled();expect(mocks.fail).toHaveBeenCalled();});
	it('does not add a duplicate timeout job after an asset completes in a collecting batch',async()=>{mocks.getBatch.mockResolvedValue({id:'b1',status:'collecting',lastReceivedAt:'2026-08-01T00:00:00.000Z',expiresAt:'2026-08-01T00:00:15.000Z'});await ensureBatchProcessingScheduledAfterAssetCompletion(message,env);expect(send).not.toHaveBeenCalled()});
	it('lets the already scheduled bounded continuation observe a completed asset',async()=>{mocks.getBatch.mockResolvedValue({id:'b1',status:'processing',lastReceivedAt:'2026-08-01T00:00:00.000Z',expiresAt:'2026-08-01T00:00:15.000Z',processingAt:'pending:1:current',pendingAssetWaitCount:1,continuationState:'scheduled'});await ensureBatchProcessingScheduledAfterAssetCompletion(message,env);expect(send).not.toHaveBeenCalled()});
	it('does not enqueue work when a completed asset message is redelivered',async()=>{mocks.claim.mockResolvedValue('completed');await processImageMessage(message,env);expect(mocks.download).not.toHaveBeenCalled();expect(send).not.toHaveBeenCalled()});
	it('preserves a late terminal asset without creating or reopening an event',async()=>{mocks.claim.mockResolvedValue('claimed_terminal');mocks.getBatch.mockResolvedValue({id:'b1',status:'needs_review',minimalEventId:'legacy-event',pendingAssetWaitCount:3,continuationState:'limit_reached'});await processImageMessage(message,env);expect(mocks.claimShell).not.toHaveBeenCalled();expect(mocks.save).not.toHaveBeenCalled();expect(mocks.complete).toHaveBeenCalledOnce();expect(send).not.toHaveBeenCalled();});
	it('acknowledges a durable asset-attempt limit with reconciliation state',async()=>{mocks.claim.mockResolvedValue('attempt_limit');await processImageMessage(message,env);expect(mocks.markAttemptLimit).toHaveBeenCalledWith(env.DB,'b1','line-message-m1');expect(mocks.download).not.toHaveBeenCalled();});
});
