import { env } from 'cloudflare:test';
import { beforeAll,beforeEach,describe,expect,it,vi } from 'vitest';
import type { WorkerEnv } from '../types/env';
import { runAgentSubmissionReconciliation } from './agent-submission-reconciliation';

const schema=`CREATE TABLE IF NOT EXISTS agent_submissions(id TEXT PRIMARY KEY,source TEXT NOT NULL,conversation_key TEXT NOT NULL,push_target TEXT,status TEXT NOT NULL,first_received_at TEXT NOT NULL,last_received_at TEXT NOT NULL,closed_at TEXT,workflow_instance_id TEXT UNIQUE,result_event_id TEXT,result_action TEXT,error_code TEXT,error_message TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,image_set_id TEXT,expected_image_count INTEGER,grouping_strategy TEXT,done_requested_at TEXT,done_settle_until TEXT,closure_reason TEXT,append_race_count INTEGER NOT NULL DEFAULT 0,webhook_event_count INTEGER NOT NULL DEFAULT 0,image_event_count INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS agent_submission_items(id TEXT PRIMARY KEY,submission_id TEXT NOT NULL,source_message_id TEXT NOT NULL UNIQUE,webhook_event_id TEXT UNIQUE,item_type TEXT NOT NULL,asset_id TEXT UNIQUE,intake_id TEXT,r2_object_key TEXT,content_type TEXT,text_content TEXT,source_url TEXT,ordinal INTEGER NOT NULL,received_at TEXT NOT NULL,created_at TEXT NOT NULL,image_set_id TEXT,image_set_index INTEGER,image_set_total INTEGER,webhook_batch_id TEXT,append_race_resolved INTEGER NOT NULL DEFAULT 0,UNIQUE(submission_id,ordinal));`;
beforeAll(async()=>{await env.DB.exec(schema);});
beforeEach(async()=>{await env.DB.exec('DELETE FROM agent_submission_items;DELETE FROM agent_submissions;');});

async function submission(status='collecting'){
	await env.DB.prepare("INSERT INTO agent_submissions(id,source,conversation_key,status,first_received_at,last_received_at,created_at,updated_at,expected_image_count,grouping_strategy,webhook_event_count,image_event_count) VALUES('submission-1','line_v2','user:u',?,'2026-08-04T09:00:00Z','2026-08-04T09:00:03Z','2026-08-04T09:00:00Z','2026-08-04T09:00:03Z',3,'image_set',4,3)").bind(status).run();
	for(let index=1;index<=3;index++)await env.DB.prepare("INSERT INTO agent_submission_items(id,submission_id,source_message_id,webhook_event_id,item_type,asset_id,ordinal,received_at,created_at,image_set_id,image_set_index,image_set_total) VALUES(?, 'submission-1', ?, ?, 'image', ?, ?, ?, ?, 'set-1', ?, 3)").bind(`i${index}`,`m${index}`,`w${index}`,`a${index}`,index,`2026-08-04T09:00:0${index}Z`,`2026-08-04T09:00:0${index}Z`,index).run();
	await env.DB.prepare("INSERT INTO agent_submission_items(id,submission_id,source_message_id,webhook_event_id,item_type,text_content,ordinal,received_at,created_at) VALUES('text','submission-1','mt','wt','text','details',4,'2026-08-04T09:00:03Z','2026-08-04T09:00:03Z')").run();
}
function worker(create:ReturnType<typeof vi.fn>,instances=new Map<string,any>()){return{...env,AGENT_SUBMISSION_WINDOW_SECONDS:'60',WINE_SCOUT_SUBMISSION_WORKFLOW:{create,get:vi.fn(async(id:string)=>{const found=instances.get(id);if(!found)throw new Error('instance not found');return found;})}} as unknown as WorkerEnv;}
const instance=(id='submission-1')=>({id,status:vi.fn().mockResolvedValue({status:'running'}),sendEvent:vi.fn().mockResolvedValue(undefined),restart:vi.fn(),resume:vi.fn()});

describe('agent submission reconciliation',()=>{
	it('closes a grouping window and enqueues one workflow for 1 text + 3 images',async()=>{await submission();const created=instance();const create=vi.fn().mockResolvedValue(created);const result=await runAgentSubmissionReconciliation(worker(create),{now:'2026-08-04T09:02:00Z'});expect(result).toMatchObject({selected:1,recovered:1,failed:0});expect(create).toHaveBeenCalledOnce();expect(await env.DB.prepare("SELECT status,closure_reason,workflow_instance_id FROM agent_submissions WHERE id='submission-1'").first()).toMatchObject({status:'queued',closure_reason:'reconciliation_inactivity_timeout',workflow_instance_id:'submission-1'});expect((await env.DB.prepare("SELECT COUNT(*) count FROM agent_submission_items WHERE submission_id='submission-1'").first<{count:number}>())?.count).toBe(4);});
	it('recovers a lost or failed workflow handoff on the next reconciliation without duplicating items',async()=>{await submission('queued');const create=vi.fn().mockRejectedValueOnce(new Error('enqueue unavailable'));const first=await runAgentSubmissionReconciliation(worker(create),{now:'2026-08-04T09:02:00Z'});expect(first.failed).toBe(1);const created=instance();create.mockResolvedValueOnce(created);const second=await runAgentSubmissionReconciliation(worker(create),{now:'2026-08-04T09:04:00Z'});expect(second.recovered).toBe(1);expect((await env.DB.prepare("SELECT COUNT(*) count FROM agent_submission_items WHERE submission_id='submission-1'").first<{count:number}>())?.count).toBe(4);expect(create).toHaveBeenCalledTimes(2);});
});
