import { beforeEach,describe,expect,it,vi } from 'vitest';
import type { ExtractedWineEvent } from './event-extraction';
import type { BatchAssetContext } from './batch-event-extraction';
import { recoverBatchEventsWithSingleAssetFallback } from './batch-event-fallback';

const mocks=vi.hoisted(()=>({extract:vi.fn()}));
vi.mock('./event-extraction',async(importOriginal)=>({...await importOriginal<typeof import('./event-extraction')>(),extractAndStoreEvent:mocks.extract}));
const put=vi.fn().mockResolvedValue(undefined);
const flyer=(title='Tenute Girolamo Wine Dinner',date='2026-08-05'):ExtractedWineEvent=>({isWineEvent:true,title,venue:null,address:null,date,startTime:'18:30',endTime:null,timezone:null,price:'THB 1800++',currency:'THB',bookingUrl:null,contact:null,wines:[],wineRegions:[],menu:[],notes:[],confidence:.9});
const menu:ExtractedWineEvent={isWineEvent:true,title:null,venue:null,address:null,date:null,startTime:null,endTime:null,timezone:null,price:null,currency:null,bookingUrl:null,contact:null,wines:['Wine A','Wine B'],wineRegions:[],menu:['Starter','Main course'],notes:[],confidence:.7};
const asset=(assetId:string,ocrText:string):BatchAssetContext=>({assetId,intakeId:`i-${assetId}`,ordinal:1,receivedAt:'2026-08-01T00:00:00Z',contentType:'image/jpeg',ocrText});
function completed(event:ExtractedWineEvent|null){return {status:'completed',event,model:'model'};}
beforeEach(()=>{vi.clearAllMocks();put.mockClear()});

describe('single-asset batch fallback',()=>{
	it('recovers a strong flyer and assigns a menu to the same event',async()=>{mocks.extract.mockResolvedValueOnce(completed(flyer())).mockResolvedValueOnce(completed(menu));const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[asset('flyer','TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026 18:30'),asset('menu','MENU Starter Main course Wine A Wine B')]);expect(result.events).toHaveLength(1);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}]);expect(result.unassignedAssets).toEqual([])});
	it('publishes a menu-shaped single image instead of dropping the stored image',async()=>{mocks.extract.mockResolvedValueOnce(completed(menu));const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[asset('menu','MENU Starter Main course Wine A Wine B')]);expect(result.events).toHaveLength(1);expect(result.events[0].isWineEvent).toBe(true);expect(result.events[0].assetAssignments).toEqual([{assetId:'menu',role:'main'}]);expect(result.unassignedAssets).toEqual([])});
	it('keeps a multi-image batch as one event and attaches every image',async()=>{mocks.extract.mockResolvedValueOnce(completed(flyer())).mockResolvedValueOnce(completed(flyer('Burgundy Growers Dinner','2026-08-12')));const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[asset('f1','TENUTE GIROLAMO WINE DINNER'),asset('f2','BURGUNDY GROWERS WINE DINNER')]);expect(result.events).toHaveLength(1);expect(result.events[0].assetAssignments).toEqual([{assetId:'f1',role:'main'},{assetId:'f2',role:'other'}]);expect(result.unassignedAssets).toEqual([])});
	it('applies the deterministic date hint when fallback extraction returns null',async()=>{mocks.extract.mockResolvedValueOnce(completed(flyer('Luxury Red Wine Degustation',null as unknown as string)));const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[asset('web','DETERMINISTIC EVENT DATE HINT: 2026-08-12\nWednesday 12th August 2026 . 7pm')]);expect(result.events[0]?.date).toBe('2026-08-12');});
	it('replaces a stale model year from yearless OCR using the asset received year',async()=>{mocks.extract.mockResolvedValueOnce(completed(flyer('August Wine Dinner','2021-08-06')));const dated={...asset('flyer','Thursday August 6'),receivedAt:'2026-08-03T12:00:00+07:00'};const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[dated]);expect(result.events[0]?.date).toBe('2026-08-06');});
	it('creates a generic published candidate for a completely unreadable image',async()=>{mocks.extract.mockResolvedValueOnce({status:'failed',event:null,model:'model',error:'empty context'});const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[asset('unreadable','[UNCLEAR]')]);expect(result.events[0]).toMatchObject({title:'Wine Event',date:null,venue:null,startTime:null,isWineEvent:true,assetAssignments:[{assetId:'unreadable',role:'main'}]});expect(result.ambiguous).toBe(false)});
	it('publishes an OCR-derived title when AI cannot read the title',async()=>{mocks.extract.mockResolvedValueOnce(completed({...flyer(),title:null,date:null,venue:null,startTime:null}));const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[asset('no-title','Riverside Wine Tasting\nReservations required')]);expect(result.events[0]).toMatchObject({title:'Riverside Wine Tasting',date:null,venue:null,startTime:null,isWineEvent:true})});
	it('publishes a flyer with no readable date or venue',async()=>{mocks.extract.mockResolvedValueOnce(completed({...flyer(),date:null,venue:null}));const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'b1',[asset('sparse','Cellar Selection Wine Dinner')]);expect(result.events[0]).toMatchObject({title:'Tenute Girolamo Wine Dinner',date:null,venue:null,isWineEvent:true})});
	it('recovers the exact Sunset Aperitivo flyer when batch analysis emits a spurious second event',async()=>{const sunsetOcr='Sunset Aperitivo\nAll you can eat\nBuffet\n999.-\n1,599.-\nTopps Food Hall\nTopps EATERY\nTopps WINE CELLAR\nMEET US\n6.30 - 9.30 PM\n6 AUGUST 2026\nCENTRAL CHIDLOM\nPORTO DE PHUKET\nCENTRAL RETAIL\nLINE\nScan For more INFORMATION\nLINE';mocks.extract.mockResolvedValueOnce(completed({...flyer('Sunset Aperitivo','2026-08-06'),venue:'Topps EATERY',startTime:'6.30 PM',price:'999.-'}));const result=await recoverBatchEventsWithSingleAssetFallback({} as Ai,{put} as unknown as R2Bucket,'sunset-regression',[{...asset('line-message-625672017533993479',sunsetOcr),receivedAt:'2026-08-03T12:41:27.907Z'}]);expect(result.events).toHaveLength(1);expect(result.events[0]).toMatchObject({title:'Sunset Aperitivo',date:'2026-08-06',venue:'Topps EATERY',isWineEvent:true,assetAssignments:[{assetId:'line-message-625672017533993479',role:'main'}]})});
});
