import { describe,expect,it } from 'vitest';
import type { BatchAssetContext,BatchExtractedEvent } from './batch-event-extraction';
import { attributeContributingAssets } from './deterministic-asset-attribution';

const event=(assignments:BatchExtractedEvent['assetAssignments']=[{assetId:'flyer',role:'flyer'}]):BatchExtractedEvent=>({isWineEvent:true,title:'Tenute Girolamo Wine Dinner',venue:null,address:null,date:'2026-08-05',startTime:'18:30',endTime:null,timezone:null,price:'THB 1800++',currency:'THB',bookingUrl:null,contact:null,wines:['Primitivo di Manduria','Negroamaro'],wineRegions:['Puglia'],menu:['Roasted lamb'],notes:[],confidence:.9,assetAssignments:assignments});
const asset=(assetId:string,ordinal:number,ocrText:string):BatchAssetContext=>({assetId,intakeId:`i-${assetId}`,ordinal,receivedAt:'2026-08-01T00:00:00Z',contentType:'image/jpeg',ocrText});

describe('deterministic asset attribution',()=>{
	it('promotes the identity flyer to main and links a contributing menu',()=>{const result=attributeContributingAssets([event()],[asset('flyer',1,'TENUTE GIROLAMO WINE DINNER WEDNESDAY 5TH AUGUST 2026 18:30 THB 1800'),asset('menu',2,'MENU Roasted lamb Primitivo di Manduria Negroamaro Puglia')]);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}]);expect(result.unassignedAssets).toEqual([]);expect(result.contributions.find((item)=>item.assetId==='menu')).toEqual(expect.objectContaining({assigned:true,assignedRole:'menu',contributedFields:expect.arrayContaining(['wines:Primitivo di Manduria','menu:Roasted lamb'])}))});
	it('assigns a clearly structured supplementary menu even without a surviving unique field',()=>{const candidate={...event(),wines:[],wineRegions:[],menu:[]};const result=attributeContributingAssets([candidate],[asset('flyer',1,'TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026 18:30'),asset('menu',2,'TO START\nScallop with cream\nMAIN COURSE\nRoasted lamb with sauce\nDESSERT')]);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}]);expect(result.unassignedAssets).toEqual([])});
	it('leaves a non-contributing secondary asset unassigned',()=>{const result=attributeContributingAssets([event()],[asset('flyer',1,'TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026'),asset('other',2,'PRIVATE SEATING PLAN TABLE 4')]);expect(result.unassignedAssets).toEqual(['other']);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'}])});
	it('does not attach content-only evidence arbitrarily when multiple events exist',()=>{const result=attributeContributingAssets([event([{assetId:'flyer',role:'flyer'}]),{...event([{assetId:'flyer2',role:'flyer'}]),title:'Another Wine Dinner',date:'2026-08-12'}],[asset('flyer',1,'TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026'),asset('flyer2',2,'ANOTHER WINE DINNER 12 AUGUST 2026'),asset('menu',3,'MENU Primitivo di Manduria')]);expect(result.unassignedAssets).toEqual(['menu'])});
	it('leaves a menu-like asset with a conflicting event date unassigned',()=>{const result=attributeContributingAssets([event()],[asset('flyer',1,'TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026'),asset('menu',2,'TO START\nWINE DINNER SPECIAL 12 AUGUST 2026\nMAIN COURSE\nDESSERT')]);expect(result.unassignedAssets).toEqual(['menu']);expect(result.contributions.find((item)=>item.assetId==='menu')?.conflictSignals).toContain('different event date detected: 2026-08-12 versus 2026-08-05')});
	it('keeps a correctly hinted menu assignment idempotent',()=>{const candidate=event([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}]);const assets=[asset('flyer',1,'TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026'),asset('menu',2,'TO START\nPrimitivo di Manduria\nDESSERT')];const first=attributeContributingAssets([candidate],assets);const second=attributeContributingAssets(first.events,assets);expect(second.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}])});
	it('reconciles duplicate AI ownership to at most one event',()=>{const first=event([{assetId:'shared',role:'flyer'}]);const second={...event([{assetId:'shared',role:'flyer'}]),title:'Another Wine Dinner',date:'2026-08-12'};const result=attributeContributingAssets([first,second],[asset('shared',1,'TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026')]);expect(result.events.flatMap((item)=>item.assetAssignments).filter((item)=>item.assetId==='shared')).toHaveLength(1)});
	it('handles the production-shaped five-wine menu regression',()=>{const wines=['Monte Dei Cocci Primitivo 2023','Monte Dei Cocci Primitivo DOP 2024','Monte Dei Cocci Primitivo Appassimento 2022','Risana Rosso Puglia IGP 2022','Argese Primitivo Appassimento 2023'];const candidate={...event(),title:'WINE DINNER BY CHEF ANDREA MONTELLA',wines};const flyer='TENUTE GIROLAMO\nWINE DINNER\nBY CHEF ANDREA MONTELLA\nWEDNESDAY 5TH AUGUST 2026\n18:30 HRS. ONWARDS\nTHB 1800++ PER PERSON';const menu=`TO START\n${wines.join('\n')}\nMAIN COURSE\nDESSERT`;const result=attributeContributingAssets([candidate],[asset('flyer',1,flyer),asset('menu',2,menu)]);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}]);expect(result.events[0].wines).toHaveLength(5);expect(result.unassignedAssets).toEqual([])});
});
