import { describe,expect,it } from 'vitest';
import type { BatchAssetContext,BatchExtractedEvent } from './batch-event-extraction';
import { attributeContributingAssets } from './deterministic-asset-attribution';

const candidate=(assignments:BatchExtractedEvent['assetAssignments']=[{assetId:'flyer',role:'flyer'}]):BatchExtractedEvent=>({isWineEvent:true,title:'WINE DINNER BY CHEF ANDREA MONTELLA',venue:'Centara Grand at CentralWorld',address:null,date:'2026-08-05',startTime:'18:30',endTime:null,timezone:null,price:'THB 1800++',currency:'THB',bookingUrl:null,contact:null,wines:['Monte Dei Cocci Primitivo 2023'],wineRegions:[],menu:[],notes:[],confidence:.9,assetAssignments:assignments});
const asset=(assetId:string,ordinal:number,ocrText:string):BatchAssetContext=>({assetId,intakeId:`i-${assetId}`,ordinal,receivedAt:'2026-08-01T00:00:00Z',contentType:'image/jpeg',ocrText});

describe('one-batch-one-event asset ownership',()=>{
	it('assigns every image, selecting main and menu roles',()=>{const result=attributeContributingAssets([candidate()],[asset('flyer',1,'WINE DINNER BY CHEF ANDREA MONTELLA 5 AUGUST 2026 18 30'),asset('menu',2,'TO START\nMonte Dei Cocci Primitivo 2023\nMAIN COURSE\nDESSERT')]);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}]);expect(result.unassignedAssets).toEqual([])});
	it('assigns uncertain secondary images as other instead of leaving them unresolved',()=>{const result=attributeContributingAssets([candidate()],[asset('flyer',1,'WINE DINNER BY CHEF ANDREA MONTELLA 5 AUGUST 2026'),asset('seating',2,'TABLE 1 TABLE 2')]);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'seating',role:'other'}]);expect(result.unassignedAssets).toEqual([])});
	it('uses AI roles as hints without duplicating assignments',()=>{const event=candidate([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'},{assetId:'menu',role:'other'}]);const result=attributeContributingAssets([event],[asset('flyer',1,'WINE DINNER BY CHEF ANDREA MONTELLA 5 AUGUST 2026'),asset('menu',2,'TO START\nDESSERT')]);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'other'}]);expect(new Set(result.events[0].assetAssignments.map((item)=>item.assetId)).size).toBe(2)});
	it('does not assign assets when a batch produces multiple events',()=>{const result=attributeContributingAssets([candidate(),{...candidate(),title:'Another Dinner'}],[asset('one',1,'image one'),asset('two',2,'image two')]);expect(result.events.every((event)=>event.assetAssignments.length===0)).toBe(true);expect(result.unassignedAssets).toEqual(['one','two'])});
	it('keeps menu-only batches without an event unresolved',()=>{const result=attributeContributingAssets([],[asset('menu',1,'TO START\nMAIN COURSE\nDESSERT')]);expect(result.events).toEqual([]);expect(result.unassignedAssets).toEqual(['menu'])});
	it('handles the exact production-shaped flyer and five-wine menu',()=>{const wines=['Monte Dei Cocci Primitivo 2023','Monte Dei Cocci Primitivo DOP 2024','Monte Dei Cocci Primitivo Appassimento 2022','Risana Rosso Puglia IGP 2022','Argese Primitivo Appassimento 2023'];const event={...candidate(),wines};const flyer='TENUTE GIROLAMO\nWINE DINNER\nBY CHEF ANDREA MONTELLA\nWEDNESDAY 5TH AUGUST 2026\n18:30 HRS. ONWARDS\nTHB 1800++ PER PERSON\nTenute Girolamo is not just a winery...';const menu=`TO START\n${wines.join('\n')}\nMAIN COURSE\nDESSERT`;const result=attributeContributingAssets([event],[asset('flyer',1,flyer),asset('menu',2,menu)]);expect(result.events[0].assetAssignments).toEqual([{assetId:'flyer',role:'main'},{assetId:'menu',role:'menu'}]);expect(result.unassignedAssets).toEqual([])});
});
