import { env } from 'cloudflare:test';
import { beforeAll,beforeEach,describe,expect,it } from 'vitest';
import { claimBatchForDone,claimClosedBatch,claimReadyBatch,closeCollectingBatch,completeBatch,getBatch,listBatchAssets,listBatchTexts,registerBatchAsset,registerBatchText } from './line-image-batch-repository';

beforeAll(async()=>{await env.DB.exec(`CREATE TABLE IF NOT EXISTS line_image_batches (id TEXT PRIMARY KEY,conversation_key TEXT NOT NULL,status TEXT NOT NULL,first_received_at TEXT NOT NULL,last_received_at TEXT NOT NULL,created_at TEXT NOT NULL,last_activity_at TEXT NOT NULL,expires_at TEXT NOT NULL,closed_at TEXT,updated_at TEXT NOT NULL,processing_at TEXT,completed_at TEXT,push_target TEXT,resulting_event_ids_json TEXT NOT NULL DEFAULT '[]',error TEXT,attempt_count INTEGER NOT NULL DEFAULT 0,notification_sent_at TEXT);CREATE TABLE IF NOT EXISTS line_image_batch_assets(batch_id TEXT NOT NULL,asset_id TEXT NOT NULL,intake_id TEXT NOT NULL,line_message_id TEXT NOT NULL UNIQUE,webhook_event_id TEXT UNIQUE,source_type TEXT NOT NULL DEFAULT 'line_image',source_reference TEXT NOT NULL,content_type TEXT NOT NULL,r2_object_key TEXT NOT NULL,received_at TEXT NOT NULL,conversation_key TEXT NOT NULL,ordinal INTEGER NOT NULL,PRIMARY KEY(batch_id,asset_id),UNIQUE(asset_id));CREATE TABLE IF NOT EXISTS line_message_batch_texts(batch_id TEXT NOT NULL,message_id TEXT NOT NULL UNIQUE,webhook_event_id TEXT UNIQUE,asset_id TEXT NOT NULL UNIQUE,text_content TEXT NOT NULL,received_at TEXT NOT NULL,conversation_key TEXT NOT NULL,ordinal INTEGER NOT NULL,PRIMARY KEY(batch_id,message_id));CREATE UNIQUE INDEX IF NOT EXISTS test_collecting_conversation ON line_image_batches(conversation_key) WHERE status='collecting';`)});
beforeEach(async()=>{await env.DB.prepare('DELETE FROM line_message_batch_texts').run();await env.DB.prepare('DELETE FROM line_image_batch_assets').run();await env.DB.prepare('DELETE FROM line_image_batches').run()});
const input=(id:string,time:string)=>({assetId:`a${id}`,intakeId:`i${id}`,lineMessageId:`m${id}`,contentType:'image/jpeg',r2ObjectKey:`o${id}`,receivedAt:time,conversationKey:'user:u1'});
describe('LINE image batch CAS',()=>{
	it('extends one collecting batch and rejects a stale scheduled claim',async()=>{const first=await registerBatchAsset(env.DB,input('1','2026-08-01T00:00:00.000Z'));const second=await registerBatchAsset(env.DB,input('2','2026-08-01T00:00:10.000Z'));expect(second.batch.id).toBe(first.batch.id);expect((await listBatchAssets(env.DB,first.batch.id))).toHaveLength(2);expect(await claimReadyBatch(env.DB,first.batch.id,first.batch.lastReceivedAt,'2026-08-01T00:01:00.000Z')).toBeNull()});
	it('allows only one concurrent claim and makes a late image start a new batch',async()=>{const registered=await registerBatchAsset(env.DB,input('1','2026-08-01T00:00:00.000Z'));const [a,b]=await Promise.all([claimReadyBatch(env.DB,registered.batch.id,registered.batch.lastReceivedAt,'2026-08-01T00:01:00.000Z'),claimReadyBatch(env.DB,registered.batch.id,registered.batch.lastReceivedAt,'2026-08-01T00:01:00.000Z')]);expect([a,b].filter(Boolean)).toHaveLength(1);const late=await registerBatchAsset(env.DB,input('2','2026-08-01T00:00:20.000Z'));expect(late.batch.id).not.toBe(registered.batch.id);expect((await getBatch(env.DB,registered.batch.id))?.status).toBe('processing')});
	it('deduplicates a repeated LINE message',async()=>{const one=await registerBatchAsset(env.DB,input('1','2026-08-01T00:00:00.000Z'));const two=await registerBatchAsset(env.DB,input('1','2026-08-01T00:00:00.000Z'));expect(two.duplicate).toBe(true);expect(two.batch.id).toBe(one.batch.id);expect(await listBatchAssets(env.DB,one.batch.id)).toHaveLength(1)});
	it('deduplicates by webhook event id even if a retry has a different message id',async()=>{const one=await registerBatchAsset(env.DB,{...input('1','2026-08-01T00:00:00.000Z'),webhookEventId:'evt-1'});const two=await registerBatchAsset(env.DB,{...input('2','2026-08-01T00:00:01.000Z'),webhookEventId:'evt-1'});expect(two.duplicate).toBe(true);expect(two.batch.id).toBe(one.batch.id);expect(await listBatchAssets(env.DB,one.batch.id)).toHaveLength(1)});
	it('groups text and image messages and extends the same batch',async()=>{const text=await registerBatchText(env.DB,{messageId:'t1',text:'Venue details',receivedAt:'2026-08-01T00:00:00Z',conversationKey:'user:u1'});const image=await registerBatchAsset(env.DB,input('1','2026-08-01T00:00:20Z'));expect(image.batch.id).toBe(text.batch.id);expect(await listBatchTexts(env.DB,text.batch.id)).toHaveLength(1);expect(image.batch.lastReceivedAt).toBe('2026-08-01T00:00:20Z')});
	it('starts a clean batch after sixty seconds and never carries stale text forward',async()=>{const text=await registerBatchText(env.DB,{messageId:'t1',text:'Old event',receivedAt:'2026-08-01T00:00:00Z',conversationKey:'user:u1'});const image=await registerBatchAsset(env.DB,input('1','2026-08-01T00:01:00Z'));expect(image.batch.id).not.toBe(text.batch.id);expect(await listBatchTexts(env.DB,image.batch.id)).toEqual([]);expect((await getBatch(env.DB,text.batch.id))?.status).toBe('processing')});
	it('creates a new batch for the first image after done',async()=>{const first=await registerBatchAsset(env.DB,input('1','2026-08-01T00:00:00Z'));await closeCollectingBatch(env.DB,'user:u1','2026-08-01T00:00:10Z');const next=await registerBatchAsset(env.DB,input('2','2026-08-01T00:00:20Z'));expect(next.batch.id).not.toBe(first.batch.id);expect(await listBatchAssets(env.DB,next.batch.id)).toHaveLength(1)});
	it('atomically closes and claims a batch for /done only once',async()=>{await registerBatchText(env.DB,{messageId:'t1',text:'Details',receivedAt:'2026-08-01T00:00:00Z',conversationKey:'user:u1'});const closed=await closeCollectingBatch(env.DB,'user:u1','2026-08-01T00:00:10Z');expect(closed?.status).toBe('processing');expect(await closeCollectingBatch(env.DB,'user:u1','2026-08-01T00:00:10Z')).toBeNull();expect(await claimClosedBatch(env.DB,closed!.id,closed!.processingAt!)).not.toBeNull();expect(await claimClosedBatch(env.DB,closed!.id,closed!.processingAt!)).toBeNull()});
	it('claims a collecting batch for done at and after its expiration boundary',async()=>{for(const [id,doneAt] of [['boundary','2026-08-01T00:01:00.000Z'],['expired','2026-08-01T00:01:01.000Z']] as const){await registerBatchText(env.DB,{messageId:id,text:'Details',receivedAt:'2026-08-01T00:00:00.000Z',conversationKey:`user:${id}`},60);const result=await claimBatchForDone(env.DB,`user:${id}`,doneAt);expect(result.outcome).toBe('claimed');if(result.outcome==='claimed')expect(result.claimReason).toBe('expired');}});
	it('allows only one winner between done and the delayed queue claim',async()=>{const registered=await registerBatchText(env.DB,{messageId:'race',text:'Details',receivedAt:'2026-08-01T00:00:00.000Z',conversationKey:'user:race'},60);const [done,queue]=await Promise.all([claimBatchForDone(env.DB,'user:race','2026-08-01T00:01:00.000Z'),claimReadyBatch(env.DB,registered.batch.id,registered.batch.lastReceivedAt,'2026-08-01T00:01:00.000Z')]);expect(Number(done.outcome==='claimed')+Number(Boolean(queue))).toBe(1);expect((await claimBatchForDone(env.DB,'user:race','2026-08-01T00:01:01.000Z')).outcome).toBe('already_processing')});
	it('reports a completed batch and a truly missing batch distinctly',async()=>{const registered=await registerBatchText(env.DB,{messageId:'complete',text:'Details',receivedAt:'2026-08-01T00:00:00.000Z',conversationKey:'user:complete'});const claimed=await claimBatchForDone(env.DB,'user:complete','2026-08-01T00:00:10.000Z');expect(claimed.outcome).toBe('claimed');await completeBatch(env.DB,registered.batch.id,'completed',[]);expect((await claimBatchForDone(env.DB,'user:complete','2026-08-01T00:00:20.000Z')).outcome).toBe('already_completed');expect((await claimBatchForDone(env.DB,'user:missing')).outcome).toBe('not_found')});
	it('persists the configured ninety-second expiration window',async()=>{const registered=await registerBatchText(env.DB,{messageId:'window',text:'Details',receivedAt:'2026-08-01T00:00:00.000Z',conversationKey:'user:window'},90);expect(registered.batch.expiresAt).toBe('2026-08-01T00:01:30.000Z')});
});
