import { beforeEach,describe,expect,it,vi } from 'vitest';
import type { WorkerEnv } from '../types/env';
import { processImageBatch } from './line-image-batch-processing';

const mocks=vi.hoisted(()=>({getBatch:vi.fn(),claim:vi.fn(),list:vi.fn(),listTexts:vi.fn(),listWeb:vi.fn(),complete:vi.fn(),markNotification:vi.fn(),ocr:vi.fn(),batchExtract:vi.fn(),fallback:vi.fn(),save:vi.fn(),push:vi.fn()}));
vi.mock('../config',()=>({getOptionalAiEventResolutionOptions:vi.fn(),getLineMessageBatchWindowSeconds:vi.fn().mockReturnValue(60)}));
vi.mock('./line-image-batch-repository',()=>({getBatch:mocks.getBatch,claimReadyBatch:mocks.claim,claimClosedBatch:vi.fn(),listBatchAssets:mocks.list,listBatchTexts:mocks.listTexts,listBatchWebSources:mocks.listWeb,completeBatch:mocks.complete,markBatchNotificationSent:mocks.markNotification,retryFailedBatch:vi.fn(),failBatch:vi.fn()}));
vi.mock('./ocr',()=>({extractAndStoreOcr:mocks.ocr}));
vi.mock('./batch-event-extraction',()=>({extractBatchEvents:mocks.batchExtract}));
vi.mock('./batch-event-fallback',()=>({recoverBatchEventsWithSingleAssetFallback:mocks.fallback}));
vi.mock('./event-repository',async(importOriginal)=>({...await importOriginal<typeof import('./event-repository')>(),saveWineEvent:mocks.save}));
vi.mock('./line-text-context',()=>({claimLineTextContext:vi.fn().mockResolvedValue(null),markLineTextContextLinked:vi.fn()}));
vi.mock('./line',()=>({pushToLine:mocks.push}));

const candidate={isWineEvent:true,title:'Tenute Girolamo Wine Dinner',venue:null,address:null,date:'2026-08-05',startTime:'18:30',endTime:null,timezone:null,price:'THB 1800++',currency:'THB',bookingUrl:null,contact:null,wines:['Wine A'],wineRegions:[],menu:['Dish'],notes:[],confidence:.9,assetAssignments:[{assetId:'a1',role:'flyer'},{assetId:'a2',role:'menu'}]};
const diagnostics={model:'model',rawResponse:{},parseSuccess:true,parseError:null,schemaValidationSuccess:true,schemaValidationError:null,fallbackRequired:true,fallbackReason:'batch analysis returned zero events'};
const bucket={get:vi.fn().mockResolvedValue({arrayBuffer:vi.fn().mockResolvedValue(new Uint8Array([1]).buffer)}),put:vi.fn().mockResolvedValue(undefined)};
const env={DB:{},AI:{},EVENT_INTAKES:bucket,IMAGE_PROCESSING_QUEUE:{},LINE_IMAGE_BATCH_WINDOW_SECONDS:'15'} as unknown as WorkerEnv;

beforeEach(()=>{vi.clearAllMocks();const batch={id:'b1',status:'collecting',lastReceivedAt:'2026-01-01T00:00:00.000Z',pushTarget:null};mocks.getBatch.mockResolvedValue(batch);mocks.claim.mockResolvedValue({...batch,status:'processing'});mocks.list.mockResolvedValue([{batchId:'b1',assetId:'a1',intakeId:'i1',lineMessageId:'m1',contentType:'image/jpeg',r2ObjectKey:'o1',receivedAt:'2026-01-01T00:00:00Z',conversationKey:'user:u',ordinal:1},{batchId:'b1',assetId:'a2',intakeId:'i2',lineMessageId:'m2',contentType:'image/jpeg',r2ObjectKey:'o2',receivedAt:'2026-01-01T00:00:01Z',conversationKey:'user:u',ordinal:2}]);mocks.listTexts.mockResolvedValue([]);mocks.listWeb.mockResolvedValue([]);mocks.ocr.mockResolvedValueOnce({status:'completed',text:'TENUTE GIROLAMO WINE DINNER 5 AUGUST 2026 18:30',model:'ocr'}).mockResolvedValueOnce({status:'completed',text:'MENU Dish Wine A Wine B',model:'ocr'});mocks.complete.mockResolvedValue(true);mocks.save.mockResolvedValue({id:'event-1',duplicate:false})});

describe('batch processing fallback integration',()=>{
	it('publishes one recovered flyer event with its menu asset',async()=>{mocks.batchExtract.mockResolvedValue({events:[],unassignedAssets:['a1','a2'],ambiguous:true,diagnostics});mocks.fallback.mockResolvedValue({events:[candidate],unassignedAssets:[],ambiguous:false,diagnostics:[]});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.fallback).toHaveBeenCalledOnce();expect(mocks.save).toHaveBeenCalledOnce();expect(mocks.save.mock.calls[0][1]).toEqual(expect.objectContaining({assetId:'a1',assetRole:'main',relatedAssets:[expect.objectContaining({assetId:'a2',assetRole:'menu'})]}));expect(mocks.complete).toHaveBeenCalledWith(env.DB,'b1','completed',['event-1'])});
	it('does not invoke fallback when batch analysis succeeds normally',async()=>{mocks.batchExtract.mockResolvedValue({events:[candidate],unassignedAssets:[],ambiguous:false,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.fallback).not.toHaveBeenCalled();expect(mocks.save).toHaveBeenCalledOnce()});
	it('links a menu deterministically when its wine survives but AI leaves it unassigned',async()=>{mocks.batchExtract.mockResolvedValue({events:[{...candidate,assetAssignments:[{assetId:'a1',role:'flyer'}]}],unassignedAssets:['a2'],ambiguous:true,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.fallback).not.toHaveBeenCalled();expect(mocks.save.mock.calls[0][1]).toEqual(expect.objectContaining({assetRole:'main',relatedAssets:[expect.objectContaining({assetId:'a2',assetRole:'menu'})]}));expect(mocks.complete).toHaveBeenCalledWith(env.DB,'b1','completed',['event-1'])});
	it('completes the production marketing-copy flyer and menu batch without review',async()=>{const wines=['Monte Dei Cocci Primitivo 2023','Monte Dei Cocci Primitivo DOP 2024','Monte Dei Cocci Primitivo Appassimento 2022','Risana Rosso Puglia IGP 2022','Argese Primitivo Appassimento 2023'];const flyer='TENUTE GIROLAMO\nWINE DINNER\nBY CHEF ANDREA MONTELLA\nWEDNESDAY 5TH AUGUST 2026\n18:30 HRS. ONWARDS\nTHB 1800++ PER PERSON\nTenute Girolamo is not just a winery...';const menu=`TO START\n${wines.join('\n')}\nMAIN COURSE\nDESSERT`;mocks.ocr.mockReset().mockResolvedValueOnce({status:'completed',text:flyer,model:'ocr'}).mockResolvedValueOnce({status:'completed',text:menu,model:'ocr'});mocks.batchExtract.mockResolvedValue({events:[{...candidate,title:'WINE DINNER BY CHEF ANDREA MONTELLA',venue:'Centara Grand at CentralWorld',wines,assetAssignments:[{assetId:'a1',role:'flyer'}]}],unassignedAssets:['a2'],ambiguous:true,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.save.mock.calls[0][1]).toEqual(expect.objectContaining({assetRole:'main',relatedAssets:[expect.objectContaining({assetId:'a2',assetRole:'menu'})],event:expect.objectContaining({wines})}));expect(mocks.complete).toHaveBeenCalledWith(env.DB,'b1','completed',['event-1'])});
	it('sends a successful mixed-batch summary without a review suffix',async()=>{const batch={id:'b1',status:'collecting',lastReceivedAt:'2026-01-01T00:00:00.000Z',pushTarget:'user:u'};mocks.getBatch.mockResolvedValue(batch);mocks.claim.mockResolvedValue({...batch,status:'processing'});mocks.listTexts.mockResolvedValue([{batchId:'b1',messageId:'t1',assetId:'line-text-t1',text:'Booking details',receivedAt:'2026-01-01T00:00:02Z',conversationKey:'user:u',ordinal:3}]);mocks.batchExtract.mockResolvedValue({events:[candidate],unassignedAssets:[],ambiguous:false,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});mocks.markNotification.mockResolvedValue(true);await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.push).toHaveBeenCalledWith('user:u','Processed 2 images and 1 text message and published 1 event: Tenute Girolamo Wine Dinner.',undefined);expect(mocks.push.mock.calls[0][1]).not.toContain('review')});
	it('includes all batch text in extraction and links it contextually',async()=>{mocks.listTexts.mockResolvedValue([{batchId:'b1',messageId:'t1',assetId:'line-text-t1',text:'Booking: https://example.com/book',receivedAt:'2026-01-01T00:00:02Z',conversationKey:'user:u',ordinal:3}]);mocks.batchExtract.mockResolvedValue({events:[candidate],unassignedAssets:[],ambiguous:false,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.batchExtract.mock.calls[0][3][0].lineText).toContain('Booking: https://example.com/book');expect(mocks.save.mock.calls[0][1].relatedAssets).toEqual(expect.arrayContaining([expect.objectContaining({assetId:'line-text-t1',sourceType:'line_text',isPublic:false})]))});
	it('publishes a valid text-only batch and rejects an incomplete one',async()=>{mocks.list.mockResolvedValue([]);mocks.listTexts.mockResolvedValue([{batchId:'b1',messageId:'t1',assetId:'line-text-t1',text:'Bangkok Grand Wine Dinner 5 August 2026 19:00 at Cellar Hall',receivedAt:'2026-01-01T00:00:00Z',conversationKey:'user:u',ordinal:1}]);mocks.batchExtract.mockResolvedValue({events:[candidate],unassignedAssets:[],ambiguous:false,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.save.mock.calls[0][1]).toEqual(expect.objectContaining({assetId:'line-text-t1',sourceType:'line_text'}));mocks.save.mockClear();mocks.complete.mockClear();mocks.batchExtract.mockResolvedValue({events:[{...candidate,title:null,date:null,startTime:null,isWineEvent:false,assetAssignments:[]}],unassignedAssets:[],ambiguous:false,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.save).not.toHaveBeenCalled();expect(mocks.complete).toHaveBeenCalledWith(env.DB,'b1','needs_review',[])});
	it('backfills a missing LLM date from server-rendered webpage text',async()=>{mocks.list.mockResolvedValue([]);mocks.listWeb.mockResolvedValue([{batchId:'b1',messageId:'w1',webhookEventId:'we1',assetId:'line-web-w1',requestedUrl:'https://mittonwines.co.th/event',normalizedUrl:'https://mittonwines.co.th/event',finalUrl:'https://mittonwines.co.th/event',status:'completed',httpStatus:200,contentType:'text/html',responseBytes:1000,redirectCount:0,title:'Luxury Red Wine Degustation',description:'Wednesday 12th August 2026 . 7pm at Cento Bangkok',canonicalUrl:null,mainImageUrl:null,openGraph:{'og:title':'Luxury Red Wine Degustation'},jsonLd:[{'@type':'Product','description':'Wednesday 12th August 2026'}],extractedText:'LUXURY RED WINE DEGUSTATION\nWednesday 12th August 2026 . 7pm',originalReadableTextChars:100,extractedTextLength:67,textReduced:true,errorCode:null,errorMessage:null,fetchedAt:'2026-08-02T00:00:00Z',receivedAt:'2026-08-02T00:00:00Z',conversationKey:'user:u',ordinal:1}]);mocks.batchExtract.mockResolvedValue({events:[{...candidate,date:null,assetAssignments:[{assetId:'line-web-w1',role:'main'}]}],unassignedAssets:[],ambiguous:false,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.batchExtract.mock.calls[0][3][0].ocrText).toContain('DETERMINISTIC EVENT DATE HINT: 2026-08-12');expect(mocks.save.mock.calls[0][1]).toEqual(expect.objectContaining({sourceType:'web_page',event:expect.objectContaining({date:'2026-08-12'})}));});
	it('never publishes multiple AI event candidates',async()=>{mocks.batchExtract.mockResolvedValue({events:[candidate,{...candidate,title:'Second Event'}],unassignedAssets:[],ambiguous:false,diagnostics:{...diagnostics,fallbackRequired:false,fallbackReason:null}});await processImageBatch({type:'process_batch',batchId:'b1',expectedLastReceivedAt:'2026-01-01T00:00:00.000Z'},env);expect(mocks.save).not.toHaveBeenCalled();expect(mocks.complete).toHaveBeenCalledWith(env.DB,'b1','needs_review',[])});
});
