import type { WorkerEnv } from '../types/env';
import { extractAndStoreOcr } from './ocr';
import { fetchAndExtractWebPage, type WebPageIngestionResult } from './web-page-ingestion-service';
import { findCandidateEvents, saveWineEvent, type EventSourceAssetInput } from './event-repository';
import { matchExistingEvent } from './event-matcher';
import { normalizeWineEvent, normalizeUtf8Text, type NormalizedWineEvent } from './event-normalizer';
import { listSubmissionItems, readSubmission, saveSubmissionDiagnostics, type AgentSubmissionItem } from './agent-submission-repository';
import type { BatchAssetContext } from './batch-event-extraction';
import { runWorkersAi, type WorkersAiRequestContext } from './workers-ai-diagnostics';
import { pushToLine } from './line';

export const DEFAULT_EDITORIAL_VISION_MODEL='@cf/mistralai/mistral-small-3.1-24b-instruct';
export const MAX_EDITORIAL_IMAGE_BYTES=4*1024*1024;
export const MAX_EDITORIAL_TOTAL_IMAGE_BYTES=12*1024*1024;
export const SUPPORTED_EDITORIAL_IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp']);

export type EditorialDecision='new_event'|'update_existing_event'|'needs_review'|'not_an_event';
export type RecommendedAction='publish'|'review'|'reject';
export type EditorialAssetRole='main'|'flyer'|'menu'|'reminder'|'social'|'map'|'other';
export interface FieldEvidence {field:string;value:string|null;evidence:string[];confidence:number;}
export interface EditorialProposal {
	isWineEvent:boolean;decision:EditorialDecision;confidence:number;
	event:{title:string|null;date:string|null;startTime:string|null;endTime:string|null;venueName:string|null;venueAddress:string|null;price:string|null;currency:string|null;bookingUrl:string|null;contactPhone:string|null;contactEmail:string|null;description:string|null;wines:string[];menuItems:string[]};
	assetRoles:Array<{assetId:string;role:EditorialAssetRole}>;fieldEvidence:FieldEvidence[];uncertainties:string[];evidence:string[];recommendedAction:RecommendedAction;rawEvent?:Record<string,unknown>;
}
export type ImageInputStatus='ready'|'unsupported_type'|'oversized'|'missing';
export interface ImageInputDiagnostic {label:string;assetId:string;contentType:string|null;byteSize:number|null;status:ImageInputStatus;ocrAvailable:boolean;sentToModel:boolean;errorCode:string|null;}
export interface PreparedSubmissionContext {submissionId:string;items:AgentSubmissionItem[];labels:Record<string,string>;contexts:BatchAssetContext[];imageDiagnostics:ImageInputDiagnostic[];urlDiagnostics:WebPageIngestionResult[];contextR2Key:string;}
export type EditorialRejectionStage='json_extraction'|'schema_validation'|'candidate_normalization'|'publication_guard'|null;
export interface ValidationResult {valid:boolean;publishable:boolean;reasons:string[];normalized:NormalizedWineEvent|null;candidateCountBeforeNormalization:number;candidateCountAfterNormalization:number;rejectionStage:EditorialRejectionStage;}
export interface IdentityResolution {eventId:string|null;decision:'new'|'update'|'conflict';diagnostics:unknown;}

export interface EditorialParseDiagnostics {responseShape:string;rawModelText:string|null;jsonExtraction:{ok:boolean;source:string|null;error:string|null};parsedStructuredResponse:unknown;schemaValidationIssues:string[];candidateCountBeforeNormalization:number;request:{messages:Array<{role:string;content:string|Array<Record<string,unknown>>}>;imagePartCount:number;imageContentTypes:string[];imageByteSizes:number[];ocrTextLength:number;responseFormat:string};}
interface VisionResponse {proposal:EditorialProposal;model:string;usage:unknown;rawResponse:unknown;assetsSent:ImageInputDiagnostic[];diagnostics:EditorialParseDiagnostics;}
export interface EditorialAnalysisOutcome {proposal:EditorialProposal;model:string;includedAssetCount:number;includedImageBytes:number;diagnostics:EditorialParseDiagnostics;}
interface ContentPart {type:'text'|'image_url';text?:string;image_url?:{url:string};}
const EDITORIAL_SCHEMA={type:'object',properties:{isWineEvent:{type:'boolean'},decision:{type:'string',enum:['new_event','update_existing_event','needs_review','not_an_event']},confidence:{type:'number'},event:{type:'object',properties:{title:{type:['string','null']},date:{type:['string','null']},startTime:{type:['string','null']},endTime:{type:['string','null']},venueName:{type:['string','null']},venueAddress:{type:['string','null']},price:{type:['string','null']},currency:{type:['string','null']},bookingUrl:{type:['string','null']},contactPhone:{type:['string','null']},contactEmail:{type:['string','null']},description:{type:['string','null']},wines:{type:'array',items:{type:'string'}},menuItems:{type:'array',items:{type:'string'}}},required:['title','date','startTime','endTime','venueName','venueAddress','price','currency','bookingUrl','contactPhone','contactEmail','description','wines','menuItems'],additionalProperties:false},assetRoles:{type:'array',items:{type:'object',properties:{assetId:{type:'string'},role:{type:'string',enum:['main','flyer','menu','reminder','social','map','other']}},required:['assetId','role'],additionalProperties:false}},fieldEvidence:{type:'array',items:{type:'object',properties:{field:{type:'string'},value:{type:['string','null']},evidence:{type:'array',items:{type:'string'}},confidence:{type:'number'}},required:['field','value','evidence','confidence'],additionalProperties:false}},uncertainties:{type:'array',items:{type:'string'}},evidence:{type:'array',items:{type:'string'}},recommendedAction:{type:'string',enum:['publish','review','reject']}},required:['isWineEvent','decision','confidence','event','assetRoles','fieldEvidence','uncertainties','evidence','recommendedAction'],additionalProperties:false} as const;

function contentType(value:string|null|undefined):string|null {return value?.split(';')[0].trim().toLowerCase()||null;}
function asText(value:unknown):string|null{return typeof value==='string'&&value.trim()?value.trim():null;}
function stringArray(value:unknown):string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];}
function bytesToDataUri(bytes:ArrayBuffer,type:string):string {const view=new Uint8Array(bytes);let binary='';for(let offset=0;offset<view.length;offset+=0x8000)binary+=String.fromCharCode(...view.subarray(offset,offset+0x8000));return `data:${type};base64,${btoa(binary)}`;}
function modelText(response:unknown):{text:string|null;shape:string}{if(typeof response==='string')return{text:response,shape:'string'};if(!response||typeof response!=='object')return{text:null,shape:typeof response};const record=response as Record<string,unknown>;if(typeof record.response==='string')return{text:record.response,shape:'response'};if(record.result&&typeof record.result==='object'&&typeof (record.result as Record<string,unknown>).response==='string')return{text:(record.result as Record<string,unknown>).response as string,shape:'result.response'};const choices=record.choices;if(Array.isArray(choices)){const content=(choices[0] as {message?:{content?:unknown}}|undefined)?.message?.content;if(typeof content==='string')return{text:content,shape:'choices[0].message.content'};}return{text:null,shape:'unknown_object'};}
function extractFirstJsonObject(text:string):{value:unknown;source:string}|{error:string}{const unfenced=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();for(let start=0;start<unfenced.length;start++){if(unfenced[start]!=='{')continue;let depth=0;let quoted=false;let escaped=false;for(let index=start;index<unfenced.length;index++){const char=unfenced[index];if(quoted){if(escaped)escaped=false;else if(char==='\\')escaped=true;else if(char==='"')quoted=false;continue;}if(char==='"'){quoted=true;continue;}if(char==='{')depth++;else if(char==='}'&&--depth===0){const source=unfenced.slice(start,index+1);try{return{value:JSON.parse(source),source};}catch{break;}}} }return{error:'no valid JSON object found in model text'};}
function schemaIssues(value:unknown):string[]{const issues:string[]=[];if(!value||typeof value!=='object'||Array.isArray(value))return['$: expected object'];const raw=value as Record<string,unknown>;for(const key of EDITORIAL_SCHEMA.required)if(!(key in raw))issues.push(`$.${key}: required`);if('isWineEvent'in raw&&typeof raw.isWineEvent!=='boolean')issues.push('$.isWineEvent: expected boolean');if('decision'in raw&&!['new_event','update_existing_event','needs_review','not_an_event'].includes(String(raw.decision)))issues.push('$.decision: unsupported value');if('recommendedAction'in raw&&!['publish','review','reject'].includes(String(raw.recommendedAction)))issues.push('$.recommendedAction: unsupported value');if(!raw.event||typeof raw.event!=='object'||Array.isArray(raw.event))issues.push('$.event: expected object');else for(const key of EDITORIAL_SCHEMA.properties.event.required)if(!(key in (raw.event as Record<string,unknown>)))issues.push(`$.event.${key}: required`);for(const key of ['assetRoles','fieldEvidence','uncertainties','evidence'])if(key in raw&&!Array.isArray(raw[key]))issues.push(`$.${key}: expected array`);return issues;}
function usageFrom(response:unknown):unknown {if(!response||typeof response!=='object')return null;const record=response as Record<string,unknown>;return record.usage??(record.result&&typeof record.result==='object'?(record.result as Record<string,unknown>).usage:null)??null;}
function buildLabels(items:AgentSubmissionItem[]):Record<string,string>{const counts={image:0,text:0,url:0};return Object.fromEntries(items.map((item)=>[item.id,`${item.itemType.toUpperCase()}_${++counts[item.itemType]}`]));}
function reviewProposal(reasons:string[],evidence:string[]=[]):EditorialProposal{return{isWineEvent:false,decision:'needs_review',confidence:0,event:{title:null,date:null,startTime:null,endTime:null,venueName:null,venueAddress:null,price:null,currency:'THB',bookingUrl:null,contactPhone:null,contactEmail:null,description:null,wines:[],menuItems:[]},assetRoles:[],fieldEvidence:[],uncertainties:reasons,evidence,recommendedAction:'review'};}
function proposalFrom(value:unknown):EditorialProposal|null {if(!value||typeof value!=='object')return null;const raw=value as Record<string,unknown>;const event=raw.event&&typeof raw.event==='object'?raw.event as Record<string,unknown>:null;if(!event||typeof raw.isWineEvent!=='boolean'||typeof raw.decision!=='string'||typeof raw.recommendedAction!=='string')return null;const fieldEvidence=Array.isArray(raw.fieldEvidence)?raw.fieldEvidence.filter((item):item is FieldEvidence=>Boolean(item&&typeof item==='object'&&typeof (item as FieldEvidence).field==='string'&&Array.isArray((item as FieldEvidence).evidence)&&typeof (item as FieldEvidence).confidence==='number')):[];const assetRoles=Array.isArray(raw.assetRoles)?raw.assetRoles.filter((item):item is {assetId:string;role:EditorialAssetRole}=>Boolean(item&&typeof item==='object'&&typeof (item as {assetId?:unknown}).assetId==='string'&&typeof (item as {role?:unknown}).role==='string')):[];const proposal:EditorialProposal={isWineEvent:raw.isWineEvent,decision:raw.decision as EditorialDecision,confidence:typeof raw.confidence==='number'?Math.max(0,Math.min(1,raw.confidence)):0,event:{title:normalizeUtf8Text(asText(event.title)),date:asText(event.date),startTime:asText(event.startTime),endTime:asText(event.endTime),venueName:normalizeUtf8Text(asText(event.venueName)),venueAddress:normalizeUtf8Text(asText(event.venueAddress)),price:asText(event.price),currency:asText(event.currency)??'THB',bookingUrl:asText(event.bookingUrl),contactPhone:asText(event.contactPhone),contactEmail:asText(event.contactEmail),description:normalizeUtf8Text(asText(event.description)),wines:stringArray(event.wines),menuItems:stringArray(event.menuItems)},assetRoles,fieldEvidence,uncertainties:stringArray(raw.uncertainties),evidence:stringArray(raw.evidence),recommendedAction:raw.recommendedAction as RecommendedAction};proposal.rawEvent={isWineEvent:proposal.isWineEvent,title:proposal.event.title,date:proposal.event.date,startTime:proposal.event.startTime,endTime:proposal.event.endTime,venue:proposal.event.venueName,address:proposal.event.venueAddress,price:proposal.event.price,currency:proposal.event.currency,bookingUrl:proposal.event.bookingUrl,contactPhone:proposal.event.contactPhone,contactEmail:proposal.event.contactEmail,contact:[proposal.event.contactPhone,proposal.event.contactEmail].filter(Boolean).join(' ')||null,description:proposal.event.description,wines:proposal.event.wines,wineRegions:[],menu:proposal.event.menuItems,notes:proposal.uncertainties};return proposal;}

/** Reads source metadata and OCR, but never creates a public image URL. */
export async function prepareSubmissionContext(env:WorkerEnv,submissionId:string):Promise<PreparedSubmissionContext>{
	const submission=await readSubmission(env.DB,submissionId);if(!submission)throw new Error('submission_not_found');
	const items=await listSubmissionItems(env.DB,submissionId);const labels=buildLabels(items);const contexts:BatchAssetContext[]=[];const imageDiagnostics:ImageInputDiagnostic[]=[];const urlDiagnostics:WebPageIngestionResult[]=[];let totalImageBytes=0;
	for(const item of items){const label=labels[item.id];let sourceContent='';
		if(item.itemType==='image'){
			const type=contentType(item.contentType);let diagnostic:ImageInputDiagnostic={label,assetId:item.assetId??`submission-item-${item.id}`,contentType:type,byteSize:null,status:'missing',ocrAvailable:false,sentToModel:false,errorCode:'missing_asset_reference'};
			if(item.r2ObjectKey&&item.assetId&&item.intakeId){const head=await env.EVENT_INTAKES.head(item.r2ObjectKey);if(!head)diagnostic={...diagnostic,errorCode:'missing_r2_object'};else if(!type||!SUPPORTED_EDITORIAL_IMAGE_TYPES.has(type))diagnostic={...diagnostic,byteSize:head.size,status:'unsupported_type',errorCode:'unsupported_image_type'};else if(head.size>MAX_EDITORIAL_IMAGE_BYTES||totalImageBytes+head.size>MAX_EDITORIAL_TOTAL_IMAGE_BYTES)diagnostic={...diagnostic,byteSize:head.size,status:'oversized',errorCode:head.size>MAX_EDITORIAL_IMAGE_BYTES?'image_too_large':'submission_images_too_large'};else{totalImageBytes+=head.size;const existing=await env.EVENT_INTAKES.get(`intakes/${item.intakeId}/assets/${item.assetId}/ocr.json`);let ocr=existing?await existing.json<Awaited<ReturnType<typeof extractAndStoreOcr>>>():null;if(!ocr){const object=await env.EVENT_INTAKES.get(item.r2ObjectKey);if(object)ocr=await extractAndStoreOcr(env.AI,env.EVENT_INTAKES,{intakeId:item.intakeId,assetId:item.assetId,contentType:type,content:await object.arrayBuffer()});}diagnostic={...diagnostic,byteSize:head.size,status:'ready',ocrAvailable:ocr?.status==='completed',errorCode:null};sourceContent=`${label}\nASSET_ID: ${item.assetId}\nCONTENT_TYPE: ${type}\nBYTE_SIZE: ${head.size}\nOCR_${label}\nOCR_STATUS: ${ocr?.status??'unavailable'}\n${ocr?.text||'[unavailable]'}`;}}
			imageDiagnostics.push(diagnostic);if(!sourceContent)sourceContent=`${label}\nASSET_ID: ${diagnostic.assetId}\nCONTENT_TYPE: ${type??'[unknown]'}\nBYTE_SIZE: ${diagnostic.byteSize??'[unknown]'}\nINPUT_STATUS: ${diagnostic.status}\nERROR_CODE: ${diagnostic.errorCode}`;
		}else if(item.itemType==='url'&&item.sourceUrl){const page=await fetchAndExtractWebPage(item.sourceUrl,{timeoutMs:8_000,maxRedirects:3,maxHtmlBytes:750_000,maxExtractedTextChars:5_000,userAgent:'BangkokWineScout/2.0'});urlDiagnostics.push(page);sourceContent=`${label}\nORIGINAL_URL: ${item.sourceUrl}\nFETCH_STATUS: ${page.status}\nTITLE: ${page.title??'[unavailable]'}\nDESCRIPTION: ${page.description??'[unavailable]'}\nEXTRACTED_PAGE_CONTENT:\n${page.extractedText??'[unavailable]'}${item.textContent?`\nLINE_TEXT:\n${item.textContent}`:''}`;
		}else sourceContent=`${label}\nLINE_TEXT:\n${item.textContent??'[empty]'}`;
		contexts.push({assetId:item.assetId??`submission-item-${item.id}`,intakeId:item.intakeId??`agent-${submissionId}`,ordinal:item.ordinal,receivedAt:item.receivedAt,contentType:item.contentType??(item.itemType==='url'?'text/html':'text/plain'),ocrText:`${sourceContent}\nSOURCE_MESSAGE_ID: ${item.sourceMessageId}\nRECEIVED_AT: ${item.receivedAt}`,lineText:null});
	}
	const contextR2Key=`agent-submissions/${submissionId}/prepared-context.json`;const prepared={submissionId,items,labels,contexts,imageDiagnostics,urlDiagnostics,contextR2Key};await env.EVENT_INTAKES.put(contextR2Key,JSON.stringify(prepared,null,2),{httpMetadata:{contentType:'application/json'}});return prepared;
}

/** One joint model request containing every accepted image and every labeled source. */
export async function runEditorialVisionAnalysis(rawAi:Ai,bucket:R2Bucket,model:string,prepared:PreparedSubmissionContext,diagnosticContext:Partial<WorkersAiRequestContext>={}):Promise<VisionResponse>{
	const ai={run:(_model:string,input:unknown)=>runWorkersAi(rawAi,input,{stage:'analyse_submission',model,submissionId:prepared.submissionId,workflowInstanceId:prepared.submissionId,...diagnosticContext})} as unknown as Ai;
	const emptyDiagnostics=(issues:string[]):EditorialParseDiagnostics=>({responseShape:'not_called',rawModelText:null,jsonExtraction:{ok:false,source:null,error:'model not called'},parsedStructuredResponse:null,schemaValidationIssues:issues,candidateCountBeforeNormalization:0,request:{messages:[],imagePartCount:0,imageContentTypes:[],imageByteSizes:[],ocrTextLength:prepared.contexts.reduce((sum,item)=>sum+item.ocrText.length,0),responseFormat:'json_schema'}});
	const invalid=prepared.imageDiagnostics.filter((image)=>image.status!=='ready');if(invalid.length)return{proposal:reviewProposal(invalid.map((image)=>`${image.label}: ${image.errorCode}`),invalid.map((image)=>image.label)),model,usage:null,rawResponse:null,assetsSent:[],diagnostics:emptyDiagnostics(invalid.map((image)=>`${image.label}: ${image.errorCode}`))};
	const contextByOrdinal=new Map(prepared.contexts.map((context)=>[context.ordinal,context]));const diagnosticByAsset=new Map(prepared.imageDiagnostics.map((image)=>[image.assetId,image]));const parts:ContentPart[]=[];const assetsSent:ImageInputDiagnostic[]=[];let totalImageBytes=0;
	for(const item of prepared.items){const label=prepared.labels[item.id];const context=contextByOrdinal.get(item.ordinal);if(item.itemType!=='image'){parts.push({type:'text',text:`${context?.ocrText??label}\n--- SOURCE BOUNDARY ---`});continue;}const diagnostic=diagnosticByAsset.get(item.assetId??'');const fail=(code:string):VisionResponse=>({proposal:reviewProposal([`${label}: ${code}`],[label]),model,usage:null,rawResponse:null,assetsSent:[],diagnostics:emptyDiagnostics([`${label}: ${code}`])});if(!diagnostic||!item.r2ObjectKey)return fail('missing_asset_reference');const object=await bucket.get(item.r2ObjectKey);if(!object)return fail('missing_r2_object');const bytes=await object.arrayBuffer();const type=contentType(item.contentType);if(!type||!SUPPORTED_EDITORIAL_IMAGE_TYPES.has(type))return fail('unsupported_image_type');if(bytes.byteLength>MAX_EDITORIAL_IMAGE_BYTES)return fail('image_too_large');totalImageBytes+=bytes.byteLength;if(totalImageBytes>MAX_EDITORIAL_TOTAL_IMAGE_BYTES)return fail('submission_images_too_large');parts.push({type:'text',text:`${label}\nASSET_ID: ${diagnostic.assetId}\nCONTENT_TYPE: ${type}\nBYTE_SIZE: ${bytes.byteLength}`});parts.push({type:'image_url',image_url:{url:bytesToDataUri(bytes,type)}});parts.push({type:'text',text:`OCR_${label}\n${context?.ocrText.split(`OCR_${label}\n`)[1]??'[unavailable]'}\n--- SOURCE BOUNDARY ---`});assetsSent.push({...diagnostic,byteSize:bytes.byteLength,sentToModel:true});}
	const example={isWineEvent:true,decision:'new_event',confidence:0.95,event:{title:'Producer Wine Dinner',date:'2026-08-26',startTime:'18:00',endTime:null,venueName:'Example Bistro',venueAddress:null,price:'1490++',currency:'THB',bookingUrl:null,contactPhone:null,contactEmail:null,description:null,wines:[],menuItems:[]},assetRoles:[{assetId:'asset-id-from-input',role:'flyer'}],fieldEvidence:[{field:'title',value:'Producer Wine Dinner',evidence:['IMAGE_1'],confidence:0.95}],uncertainties:[],evidence:['IMAGE_1'],recommendedAction:'publish'};
	const system=`You are the Bangkok Wine Scout multimodal editorial analyst. Jointly inspect every supplied original image and all labeled OCR, LINE text, and URL evidence. Read visible text yourself and compare it with OCR; recover small text, telephone numbers, addresses, booking details, logos, venue identity, and layout relationships that OCR missed. Never trust OCR when it conflicts with the pixels. Distinguish the primary event flyer from menus, maps, reminders, and wine lists. Combine images only when they plausibly describe one event. Report conflicts and uncertainty explicitly. Cite source labels for important fields in fieldEvidence. Do not invent facts. Return exactly one JSON object matching the supplied schema and no prose or markdown. Every required key must be present; use null or [] when evidence is absent. Minimal valid shape example: ${JSON.stringify(example)}`;
	const request={messages:[{role:'system',content:system},{role:'user',content:parts}],temperature:0,max_tokens:2400,stream:false,response_format:{type:'json_schema',json_schema:EDITORIAL_SCHEMA}};const rawResponse=await ai.run(model,request as never) as unknown;const extractedText=modelText(rawResponse);const extraction=extractedText.text?extractFirstJsonObject(extractedText.text):{error:'model response contained no text field'};const parsedStructuredResponse='value'in extraction?extraction.value:null;const issues='value'in extraction?schemaIssues(extraction.value):[];const parsed=issues.length===0?proposalFrom(parsedStructuredResponse):null;const reason='error'in extraction?`json_extraction_failed: ${extraction.error}`:issues.length?`schema_validation_failed: ${issues.join('; ')}`:'candidate_normalization_failed: parsed schema produced no proposal';const proposal=parsed??reviewProposal([reason],prepared.items.map((item)=>prepared.labels[item.id]));const sanitizedParts=parts.map((part)=>part.type==='image_url'?{type:'image_url',image_url:{url:'[base64 payload omitted]'}}:{type:'text',text:part.text??''});const diagnostics:EditorialParseDiagnostics={responseShape:extractedText.shape,rawModelText:extractedText.text,jsonExtraction:'value'in extraction?{ok:true,source:extraction.source,error:null}:{ok:false,source:null,error:extraction.error},parsedStructuredResponse,schemaValidationIssues:issues,candidateCountBeforeNormalization:parsed?1:0,request:{messages:[{role:'system',content:system},{role:'user',content:sanitizedParts}],imagePartCount:assetsSent.length,imageContentTypes:assetsSent.map((asset)=>asset.contentType).filter((value):value is string=>Boolean(value)),imageByteSizes:assetsSent.map((asset)=>asset.byteSize??0),ocrTextLength:prepared.contexts.reduce((sum,item)=>sum+item.ocrText.length,0),responseFormat:'json_schema'}};return{proposal,model,usage:usageFrom(rawResponse),rawResponse,assetsSent,diagnostics};
}

/** Controlled reasoning boundary: the model receives no database write capability. */
export async function analyseSubmissionWithDiagnostics(env:WorkerEnv,prepared:PreparedSubmissionContext,diagnosticContext:Partial<WorkersAiRequestContext>={}):Promise<EditorialAnalysisOutcome>{const model=env.EDITORIAL_VISION_MODEL?.trim()||DEFAULT_EDITORIAL_VISION_MODEL;const result=await runEditorialVisionAnalysis(env.AI,env.EVENT_INTAKES,model,prepared,{accountId:env.CLOUDFLARE_ACCOUNT_ID,...diagnosticContext});const rawKey=`agent-submissions/${prepared.submissionId}/ai-result.json`;await env.EVENT_INTAKES.put(rawKey,JSON.stringify({model:result.model,assetsSent:result.assetsSent,ocrAvailability:prepared.imageDiagnostics.map(({label,ocrAvailable})=>({label,ocrAvailable})),usage:result.usage,proposal:result.proposal,diagnostics:result.diagnostics,rawResponse:result.rawResponse},null,2),{httpMetadata:{contentType:'application/json'}});await saveSubmissionDiagnostics(env.DB,prepared.submissionId,{aiResult:result.proposal,uncertainties:result.proposal.uncertainties,urls:prepared.urlDiagnostics,rawAiR2Key:rawKey});return{proposal:result.proposal,model:result.model,includedAssetCount:result.assetsSent.length,includedImageBytes:result.assetsSent.reduce((sum,asset)=>sum+(asset.byteSize??0),0),diagnostics:result.diagnostics};}
export async function analyseSubmission(env:WorkerEnv,prepared:PreparedSubmissionContext):Promise<EditorialProposal>{return(await analyseSubmissionWithDiagnostics(env,prepared)).proposal;}

export function validateEditorialProposal(proposal:EditorialProposal,prepared:PreparedSubmissionContext):ValidationResult{const reasons:string[]=[];if(!Number.isFinite(proposal.confidence)||proposal.confidence<0||proposal.confidence>1)reasons.push('confidence is outside 0..1');if(!['new_event','update_existing_event','needs_review','not_an_event'].includes(proposal.decision))reasons.push('unsupported decision');if(!proposal.rawEvent){const parseReason=proposal.uncertainties.find((reason)=>reason.startsWith('json_extraction_failed:')||reason.startsWith('schema_validation_failed:')||reason.startsWith('candidate_normalization_failed:'))??'no structured event candidate';const rejectionStage:EditorialRejectionStage=parseReason.startsWith('json_extraction_failed:')?'json_extraction':parseReason.startsWith('schema_validation_failed:')?'schema_validation':'candidate_normalization';return{valid:false,publishable:false,reasons:[...reasons,parseReason],normalized:null,candidateCountBeforeNormalization:0,candidateCountAfterNormalization:0,rejectionStage};}const normalized=normalizeWineEvent({...proposal.rawEvent,isWineEvent:proposal.isWineEvent,title:undefined} as never);const title=proposal.event.title?.trim()??'';if(title.length<5||['wine event','event','untitled'].includes(title.toLowerCase()))reasons.push('meaningful title is required');if(!normalized.date)reasons.push('valid event date is required');if(!normalized.isWineEvent)reasons.push('wine-event evidence is required');const completeEvidence=prepared.contexts.map((context)=>context.ocrText).join('\n');const locationEvidence=Boolean(normalized.venue?.trim()||normalized.address?.trim()||normalized.district?.trim())&&(/bangkok|กรุงเทพ/i.test(completeEvidence)||Boolean(normalized.venue?.trim()));if(!locationEvidence)reasons.push('Bangkok-relevant venue or location evidence is required');const onlySupplementary=proposal.assetRoles.length>0&&proposal.assetRoles.every((asset)=>['menu','map','reminder'].includes(asset.role));if(onlySupplementary)reasons.push('menu/map/reminder-only submission cannot create an event');if(proposal.decision==='needs_review'||proposal.recommendedAction!=='publish')reasons.push('AI requested review or rejection');return{valid:true,publishable:reasons.length===0,reasons,normalized,candidateCountBeforeNormalization:1,candidateCountAfterNormalization:1,rejectionStage:reasons.length?'publication_guard':null};}
export async function resolveEventIdentity(env:WorkerEnv,proposal:EditorialProposal,normalized:NormalizedWineEvent):Promise<IdentityResolution>{const incoming={title:proposal.event.title,date:normalized.date,startTime:normalized.startTime,venue:normalized.venue};const candidates=await findCandidateEvents(env.DB,incoming);const individuallyMatched=candidates.filter((candidate)=>matchExistingEvent(incoming,[candidate]).matched);if(individuallyMatched.length>1)return{eventId:null,decision:'conflict',diagnostics:{candidateCount:candidates.length,strongMatches:individuallyMatched.map((candidate)=>candidate.id)}};const match=matchExistingEvent(incoming,candidates);return{eventId:match.eventId,decision:match.matched?'update':'new',diagnostics:{candidateCount:candidates.length,match}};}
export async function persistEditorialEvent(env:WorkerEnv,submissionId:string,prepared:PreparedSubmissionContext,proposal:EditorialProposal,normalized:NormalizedWineEvent,identity:IdentityResolution):Promise<{eventId:string;updated:boolean}>{const images=prepared.items.filter((item)=>item.itemType==='image'&&item.assetId&&item.intakeId&&item.r2ObjectKey);const primary=images.find((item)=>proposal.assetRoles.find((role)=>role.assetId===item.assetId)?.role==='main')??images[0];const fallback=primary??prepared.items[0];if(!fallback)throw new Error('submission_has_no_items');const asAsset=(item:AgentSubmissionItem):EventSourceAssetInput=>({intakeId:item.intakeId??`agent-${submissionId}`,assetId:item.assetId??`agent-item-${item.id}`,assetRole:proposal.assetRoles.find((role)=>role.assetId===item.assetId)?.role??'other',sourceType:item.itemType==='image'?'line_image':item.itemType==='url'?'web_page':'line_text',sourceMessageId:item.sourceMessageId,textContent:item.textContent??undefined,isPublic:item.itemType==='image',r2ObjectKey:item.r2ObjectKey??undefined,contentType:item.contentType??undefined});const result=await saveWineEvent(env.DB,{eventId:identity.eventId??`agent:${submissionId}`,intakeId:fallback.intakeId??`agent-${submissionId}`,assetId:fallback.assetId??`agent-item-${fallback.id}`,assetRole:primary?'main':'other',sourceType:fallback.itemType==='image'?'line_image':fallback.itemType==='url'?'web_page':'line_text',sourceMessageId:fallback.sourceMessageId,isPublic:fallback.itemType==='image',r2ObjectKey:fallback.r2ObjectKey??undefined,contentType:fallback.contentType??undefined,title:proposal.event.title,event:normalized,relatedAssets:prepared.items.filter((item)=>item.id!==fallback.id).map(asAsset)});if(!result.duplicate&&env.ADMIN_LINE_USER_ID?.trim()){try{const row=await env.DB.prepare('SELECT slug FROM events WHERE id=? LIMIT 1').bind(result.id).first<{slug:string|null}>();if(!row?.slug)throw new Error('created_event_slug_missing');const message=`🍷 New event posted\n\n${proposal.event.title??'Wine event'}\n${normalized.date??'Date to be announced'} · ${normalized.venue??'Venue to be announced'}\n\nhttps://bangkokwinescout.com/events/${encodeURIComponent(row.slug)}`;await pushToLine(env.ADMIN_LINE_USER_ID.trim(),message,env.LINE_V2_CHANNEL_ACCESS_TOKEN?.trim()||env.LINE_CHANNEL_ACCESS_TOKEN);}catch(error){console.error(JSON.stringify({component:'agent_submission_v2',event:'admin_notification_failed',eventId:result.id,error:error instanceof Error?error.message:String(error)}));}}return{eventId:result.id,updated:result.duplicate};}
export async function readPublishedEventSummary(db:D1Database,eventId:string):Promise<{title:string;slug:string|null}>{const row=await db.prepare('SELECT title,slug FROM events WHERE id=? LIMIT 1').bind(eventId).first<{title:string|null;slug:string|null}>();return{title:row?.title??'Wine event',slug:row?.slug??null};}
