import { describe,expect,it,vi } from 'vitest';
import { MAX_EDITORIAL_IMAGE_BYTES,MAX_EDITORIAL_TOTAL_IMAGE_BYTES,runEditorialVisionAnalysis,validateEditorialProposal,type EditorialProposal,type ImageInputDiagnostic,type PreparedSubmissionContext } from './wine-scout-editorial-agent';
import type { AgentSubmissionItem } from './agent-submission-repository';

function item(id:string,type:AgentSubmissionItem['itemType'],ordinal:number,overrides:Partial<AgentSubmissionItem>={}):AgentSubmissionItem{return{id,submissionId:'s1',sourceMessageId:`message-${id}`,webhookEventId:`webhook-${id}`,itemType:type,assetId:type==='image'?`asset-${id}`:null,intakeId:type==='image'?`intake-${id}`:null,r2ObjectKey:type==='image'?`r2-${id}`:null,contentType:type==='image'?'image/jpeg':type==='url'?'text/uri-list':'text/plain',textContent:type==='text'?`text ${id}`:null,sourceUrl:type==='url'?`https://example.com/${id}`:null,ordinal,receivedAt:`2026-08-04T00:00:0${ordinal}Z`,...overrides};}
function prepared(items:AgentSubmissionItem[],diagnostics?:ImageInputDiagnostic[]):PreparedSubmissionContext{const counts={image:0,text:0,url:0};const labels=Object.fromEntries(items.map((source)=>[source.id,`${source.itemType.toUpperCase()}_${++counts[source.itemType]}`]));return{submissionId:'s1',items,labels,contexts:items.map((source)=>({assetId:source.assetId??`submission-item-${source.id}`,intakeId:source.intakeId??'s1',ordinal:source.ordinal,receivedAt:source.receivedAt,contentType:source.contentType??'text/plain',ocrText:source.itemType==='image'?`${labels[source.id]}\nOCR_${labels[source.id]}\nOCR for ${source.id}`:`${labels[source.id]}\n${source.itemType==='url'?'EXTRACTED_PAGE_CONTENT':'LINE_TEXT'} for ${source.id}`,lineText:null})),imageDiagnostics:diagnostics??items.filter((source)=>source.itemType==='image').map((source)=>({label:labels[source.id],assetId:source.assetId!,contentType:source.contentType,byteSize:3,status:'ready',ocrAvailable:true,sentToModel:false,errorCode:null})),urlDiagnostics:[],contextR2Key:'context'};}
function validModelObject(overrides:Record<string,unknown>={}):Record<string,unknown>{return{isWineEvent:true,decision:'new_event',confidence:.95,event:{title:'Bangkok Burgundy Dinner',date:'2026-08-20',startTime:'19:00',endTime:null,venueName:'Le Venue Bangkok',venueAddress:'Bangkok',price:'3500',currency:'THB',bookingUrl:null,contactPhone:'+66 2 123 4567',contactEmail:null,description:null,wines:['Burgundy'],menuItems:[]},assetRoles:[{assetId:'asset-i1',role:'main'}],fieldEvidence:[{field:'contactPhone',value:'+66 2 123 4567',evidence:['IMAGE_1'],confidence:.94}],uncertainties:[],evidence:['IMAGE_1'],recommendedAction:'publish',...overrides};}
function modelResponse(overrides:Record<string,unknown>={}):Record<string,unknown>{return{response:JSON.stringify(validModelObject(overrides)),usage:{prompt_tokens:10}};}
function bucket(objects:Record<string,ArrayBuffer|null>){return{get:vi.fn(async(key:string)=>objects[key]?{arrayBuffer:async()=>objects[key]}:null),put:vi.fn()} as unknown as R2Bucket;}

describe('V2 joint multimodal editorial request',()=>{
	it('includes one original image as direct base64 vision input',async()=>{const source=prepared([item('i1','image',1)]);const run=vi.fn().mockResolvedValue(modelResponse());await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1,2,3]).buffer}),'vision-model',source);const request=run.mock.calls[0][1] as {messages:Array<{content:unknown}>};expect(JSON.stringify(request.messages[1].content)).toContain('data:image/jpeg;base64,AQID');});
	it('keeps multiple images in deterministic order with matching OCR labels',async()=>{const source=prepared([item('i1','image',1),item('i2','image',2)]);const run=vi.fn().mockResolvedValue(modelResponse());await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer,'r2-i2':new Uint8Array([2]).buffer}),'vision-model',source);const parts=(run.mock.calls[0][1] as {messages:Array<{content:Array<{type:string;text?:string}>}>}).messages[1].content;const text=parts.filter((part)=>part.type==='text').map((part)=>part.text).join('\n');expect(text.indexOf('IMAGE_1')).toBeLessThan(text.indexOf('IMAGE_2'));expect(text).toContain('OCR_IMAGE_1\nOCR for i1');expect(text).toContain('OCR_IMAGE_2\nOCR for i2');});
	it('includes LINE text and extracted URL evidence beside images',async()=>{const source=prepared([item('i1','image',1),item('t1','text',2),item('u1','url',3)]);const run=vi.fn().mockResolvedValue(modelResponse());await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer}),'vision-model',source);const request=JSON.stringify(run.mock.calls[0][1]);expect(request).toContain('TEXT_1');expect(request).toContain('LINE_TEXT for t1');expect(request).toContain('URL_1');expect(request).toContain('EXTRACTED_PAGE_CONTENT for u1');});
	it('routes unsupported images to review without calling the model',async()=>{const source=prepared([item('i1','image',1,{contentType:'image/gif'})],[{label:'IMAGE_1',assetId:'asset-i1',contentType:'image/gif',byteSize:3,status:'unsupported_type',ocrAvailable:false,sentToModel:false,errorCode:'unsupported_image_type'}]);const run=vi.fn();const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({}),'vision-model',source);expect(result.proposal.decision).toBe('needs_review');expect(result.proposal.uncertainties).toContain('IMAGE_1: unsupported_image_type');expect(run).not.toHaveBeenCalled();});
	it('routes oversized images to review without buffering or model calls',async()=>{const source=prepared([item('i1','image',1)],[{label:'IMAGE_1',assetId:'asset-i1',contentType:'image/jpeg',byteSize:MAX_EDITORIAL_IMAGE_BYTES+1,status:'oversized',ocrAvailable:false,sentToModel:false,errorCode:'image_too_large'}]);const run=vi.fn();const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({}),'vision-model',source);expect(result.proposal.uncertainties).toContain('IMAGE_1: image_too_large');expect(run).not.toHaveBeenCalled();});
	it('rechecks the aggregate image limit before the model call',async()=>{const items=[1,2,3,4].map((ordinal)=>item(`i${ordinal}`,'image',ordinal));const source=prepared(items);const bytes=new Uint8Array(Math.floor(MAX_EDITORIAL_TOTAL_IMAGE_BYTES/4)+1).buffer;const objects=Object.fromEntries(items.map((entry)=>[entry.r2ObjectKey!,bytes]));const run=vi.fn();const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket(objects),'vision-model',source);expect(result.proposal.uncertainties).toContain('IMAGE_4: submission_images_too_large');expect(result.assetsSent).toEqual([]);expect(run).not.toHaveBeenCalled();});
	it('turns a missing R2 object into a traceable review result',async()=>{const source=prepared([item('i1','image',1)]);const run=vi.fn();const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':null}),'vision-model',source);expect(result.proposal.uncertainties).toContain('IMAGE_1: missing_r2_object');expect(run).not.toHaveBeenCalled();});
	it('recovers an image-visible phone absent from OCR with field evidence',async()=>{const source=prepared([item('i1','image',1)]);source.contexts[0].ocrText='IMAGE_1\nOCR_IMAGE_1\nBangkok Burgundy Dinner';const run=vi.fn().mockResolvedValue(modelResponse());const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer}),'vision-model',source);expect(result.proposal.event.contactPhone).toBe('+66 2 123 4567');expect(result.proposal.fieldEvidence).toContainEqual(expect.objectContaining({field:'contactPhone',evidence:['IMAGE_1']}));});
	it('parses the exact Workers AI top-level response string shape',async()=>{const run=vi.fn().mockResolvedValue(modelResponse());const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer}),'vision-model',prepared([item('i1','image',1)]));expect(result.diagnostics.responseShape).toBe('response');expect(result.proposal.event.title).toBe('Bangkok Burgundy Dinner');});
	it.each([
		['plain JSON',(json:string)=>json],
		['markdown fences',(json:string)=>`\`\`\`json\n${json}\n\`\`\``],
		['surrounding prose',(json:string)=>`Analysis follows.\n${json}\nEnd of analysis.`],
	])('extracts valid JSON from %s',async(_label,wrap)=>{const run=vi.fn().mockResolvedValue({response:wrap(JSON.stringify(validModelObject()))});const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer}),'vision-model',prepared([item('i1','image',1)]));expect(result.diagnostics.jsonExtraction.ok).toBe(true);expect(result.proposal.event.title).toBe('Bangkok Burgundy Dinner');});
	it('reports malformed JSON at the extraction stage',async()=>{const run=vi.fn().mockResolvedValue({response:'```json\n{"event": broken}\n```'});const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer}),'vision-model',prepared([item('i1','image',1)]));expect(result.diagnostics.jsonExtraction).toEqual(expect.objectContaining({ok:false,error:'no valid JSON object found in model text'}));expect(validateEditorialProposal(result.proposal,guardPrepared).rejectionStage).toBe('json_extraction');});
	it('reports schema-invalid JSON separately from malformed JSON',async()=>{const run=vi.fn().mockResolvedValue({response:JSON.stringify({event:{name:'Wrong shape'}})});const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer}),'vision-model',prepared([item('i1','image',1)]));expect(result.diagnostics.jsonExtraction.ok).toBe(true);expect(result.diagnostics.schemaValidationIssues).toContain('$.isWineEvent: required');expect(validateEditorialProposal(result.proposal,guardPrepared).rejectionStage).toBe('schema_validation');});
	it('turns one valid flyer response into one structured and normalized candidate',async()=>{const run=vi.fn().mockResolvedValue(modelResponse());const result=await runEditorialVisionAnalysis({run} as unknown as Ai,bucket({'r2-i1':new Uint8Array([1]).buffer}),'vision-model',prepared([item('i1','image',1)]));const validation=validateEditorialProposal(result.proposal,guardPrepared);expect(result.diagnostics.candidateCountBeforeNormalization).toBe(1);expect(validation.candidateCountAfterNormalization).toBe(1);expect(validation.publishable).toBe(true);});
	it('has no model-side persistence and produces the same event identity proposal on retries',async()=>{const source=prepared([item('i1','image',1)]);const storage=bucket({'r2-i1':new Uint8Array([1]).buffer}) as unknown as {get:ReturnType<typeof vi.fn>;put:ReturnType<typeof vi.fn>};const run=vi.fn().mockResolvedValue(modelResponse());const first=await runEditorialVisionAnalysis({run} as unknown as Ai,storage as unknown as R2Bucket,'vision-model',source);const second=await runEditorialVisionAnalysis({run} as unknown as Ai,storage as unknown as R2Bucket,'vision-model',source);expect(second.proposal).toEqual(first.proposal);expect(storage.put).not.toHaveBeenCalled();});
});

const guardPrepared=prepared([item('i1','image',1)]);
function proposal(overrides:Partial<EditorialProposal>={}):EditorialProposal{const value=validModelObject() as unknown as EditorialProposal;return{...value,rawEvent:{isWineEvent:true,title:value.event.title,date:value.event.date,startTime:value.event.startTime,endTime:null,venue:value.event.venueName,address:value.event.venueAddress,price:value.event.price,currency:'THB',bookingUrl:null,contact:null,wines:['Burgundy'],wineRegions:[],menu:[],notes:[]},...overrides};}
describe('V2 deterministic publication guard',()=>{
	it('accepts a complete wine flyer',()=>expect(validateEditorialProposal(proposal(),guardPrepared).publishable).toBe(true));
	it('does not publish a menu-only submission',()=>{const result=validateEditorialProposal(proposal({assetRoles:[{assetId:'asset-i1',role:'menu'}]}),guardPrepared);expect(result.publishable).toBe(false);expect(result.reasons).toContain('menu/map/reminder-only submission cannot create an event');});
	it('routes explicit ambiguity to review',()=>expect(validateEditorialProposal(proposal({decision:'needs_review',recommendedAction:'review'}),guardPrepared).publishable).toBe(false));
	it('distinguishes candidate rejection from publication-guard rejection',()=>{const candidate=validateEditorialProposal({...proposal(),rawEvent:undefined,uncertainties:['candidate_normalization_failed: no proposal']},guardPrepared);const guard=validateEditorialProposal(proposal({assetRoles:[{assetId:'asset-i1',role:'menu'}]}),guardPrepared);expect(candidate.rejectionStage).toBe('candidate_normalization');expect(guard.rejectionStage).toBe('publication_guard');});
});
